#ifndef SDKCONFIG_H
#define SDKCONFIG_H

// Automatically generated file. DO NOT EDIT.
// Espressif IoT Development Framework (ESP-IDF) Project Configuration

#define CONFIG_IDF_CMAKE 1
#define CONFIG_IDF_TARGET_ARCH_XTENSA 1
#define CONFIG_IDF_TARGET "esp32s3"
#define CONFIG_IDF_TARGET_ESP32S3 1
#define CONFIG_IDF_FIRMWARE_CHIP_ID 0x0009


// SDK tool configuration

#define CONFIG_SDK_TOOLPREFIX "xtensa-esp32s3-elf-"
// #define CONFIG_SDK_TOOLCHAIN_SUPPORTS_TIME_WIDE_64_BITS
// end of SDK tool configuration


// Build type

#define CONFIG_APP_BUILD_TYPE_APP_2NDBOOT 1
// #define CONFIG_APP_BUILD_TYPE_ELF_RAM
#define CONFIG_APP_BUILD_GENERATE_BINARIES 1
#define CONFIG_APP_BUILD_BOOTLOADER 1
#define CONFIG_APP_BUILD_USE_FLASH_SECTIONS 1
// end of Build type


// Application manager

#define CONFIG_APP_COMPILE_TIME_DATE 1
// #define CONFIG_APP_EXCLUDE_PROJECT_VER_VAR
// #define CONFIG_APP_EXCLUDE_PROJECT_NAME_VAR
// #define CONFIG_APP_PROJECT_VER_FROM_CONFIG
#define CONFIG_APP_RETRIEVE_LEN_ELF_SHA 16
// end of Application manager


// Bootloader config

#define CONFIG_BOOTLOADER_OFFSET_IN_FLASH 0x0
#define CONFIG_BOOTLOADER_COMPILER_OPTIMIZATION_SIZE 1
// #define CONFIG_BOOTLOADER_COMPILER_OPTIMIZATION_DEBUG
// #define CONFIG_BOOTLOADER_COMPILER_OPTIMIZATION_PERF
// #define CONFIG_BOOTLOADER_COMPILER_OPTIMIZATION_NONE
#define CONFIG_BOOTLOADER_LOG_LEVEL_NONE 1
// #define CONFIG_BOOTLOADER_LOG_LEVEL_ERROR
// #define CONFIG_BOOTLOADER_LOG_LEVEL_WARN
// #define CONFIG_BOOTLOADER_LOG_LEVEL_INFO
// #define CONFIG_BOOTLOADER_LOG_LEVEL_DEBUG
// #define CONFIG_BOOTLOADER_LOG_LEVEL_VERBOSE
#define CONFIG_BOOTLOADER_LOG_LEVEL 0


// Serial Flash Configurations

// #define CONFIG_BOOTLOADER_FLASH_DC_AWARE
#define CONFIG_BOOTLOADER_FLASH_XMC_SUPPORT 1
// end of Serial Flash Configurations

#define CONFIG_BOOTLOADER_VDDSDIO_BOOST_1_9V 1
// #define CONFIG_BOOTLOADER_FACTORY_RESET
// #define CONFIG_BOOTLOADER_APP_TEST
#define CONFIG_BOOTLOADER_REGION_PROTECTION_ENABLE 1
#define CONFIG_BOOTLOADER_WDT_ENABLE 1
// #define CONFIG_BOOTLOADER_WDT_DISABLE_IN_USER_CODE
#define CONFIG_BOOTLOADER_WDT_TIME_MS 9000
#define CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE 1
// #define CONFIG_BOOTLOADER_APP_ANTI_ROLLBACK
#define CONFIG_BOOTLOADER_SKIP_VALIDATE_IN_DEEP_SLEEP 1
// #define CONFIG_BOOTLOADER_SKIP_VALIDATE_ON_POWER_ON
// #define CONFIG_BOOTLOADER_SKIP_VALIDATE_ALWAYS
#define CONFIG_BOOTLOADER_RESERVE_RTC_SIZE 0x10
// #define CONFIG_BOOTLOADER_CUSTOM_RESERVE_RTC
// end of Bootloader config


// Security features

#define CONFIG_SECURE_BOOT_SUPPORTS_RSA 1
#define CONFIG_SECURE_TARGET_HAS_SECURE_ROM_DL_MODE 1
// #define CONFIG_SECURE_SIGNED_APPS_NO_SECURE_BOOT
// #define CONFIG_SECURE_BOOT
// #define CONFIG_SECURE_FLASH_ENC_ENABLED
// end of Security features


// Boot ROM Behavior

#define CONFIG_BOOT_ROM_LOG_ALWAYS_ON 1
// #define CONFIG_BOOT_ROM_LOG_ALWAYS_OFF
// #define CONFIG_BOOT_ROM_LOG_ON_GPIO_HIGH
// #define CONFIG_BOOT_ROM_LOG_ON_GPIO_LOW
// end of Boot ROM Behavior


// Serial flasher config

#define CONFIG_ESPTOOLPY_BAUD_OTHER_VAL 115200
// #define CONFIG_ESPTOOLPY_NO_STUB
// #define CONFIG_ESPTOOLPY_OCT_FLASH
#define CONFIG_ESPTOOLPY_FLASHMODE_QIO 1
// #define CONFIG_ESPTOOLPY_FLASHMODE_QOUT
// #define CONFIG_ESPTOOLPY_FLASHMODE_DIO
// #define CONFIG_ESPTOOLPY_FLASHMODE_DOUT
#define CONFIG_ESPTOOLPY_FLASH_SAMPLE_MODE_STR 1
#define CONFIG_ESPTOOLPY_FLASHMODE "dio"
#define CONFIG_ESPTOOLPY_S3_STR 1
// #define CONFIG_ESPTOOLPY_FLASHFREQ_120M
#define CONFIG_ESPTOOLPY_FLASHFREQ_80M 1
// #define CONFIG_ESPTOOLPY_FLASHFREQ_40M
// #define CONFIG_ESPTOOLPY_FLASHFREQ_20M
#define CONFIG_ESPTOOLPY_FLASHFREQ "80m"
// #define CONFIG_ESPTOOLPY_FLASHSIZE_1MB
// #define CONFIG_ESPTOOLPY_FLASHSIZE_2MB
#define CONFIG_ESPTOOLPY_FLASHSIZE_4MB 1
// #define CONFIG_ESPTOOLPY_FLASHSIZE_8MB
// #define CONFIG_ESPTOOLPY_FLASHSIZE_16MB
// #define CONFIG_ESPTOOLPY_FLASHSIZE_32MB
// #define CONFIG_ESPTOOLPY_FLASHSIZE_64MB
// #define CONFIG_ESPTOOLPY_FLASHSIZE_128MB
#define CONFIG_ESPTOOLPY_FLASHSIZE "4MB"
#define CONFIG_ESPTOOLPY_FLASHSIZE_DETECT 1
#define CONFIG_ESPTOOLPY_BEFORE_RESET 1
// #define CONFIG_ESPTOOLPY_BEFORE_NORESET
#define CONFIG_ESPTOOLPY_BEFORE "default_reset"
#define CONFIG_ESPTOOLPY_AFTER_RESET 1
// #define CONFIG_ESPTOOLPY_AFTER_NORESET
#define CONFIG_ESPTOOLPY_AFTER "hard_reset"
// #define CONFIG_ESPTOOLPY_MONITOR_BAUD_CONSOLE
// #define CONFIG_ESPTOOLPY_MONITOR_BAUD_9600B
// #define CONFIG_ESPTOOLPY_MONITOR_BAUD_57600B
#define CONFIG_ESPTOOLPY_MONITOR_BAUD_115200B 1
// #define CONFIG_ESPTOOLPY_MONITOR_BAUD_230400B
// #define CONFIG_ESPTOOLPY_MONITOR_BAUD_921600B
// #define CONFIG_ESPTOOLPY_MONITOR_BAUD_2MB
// #define CONFIG_ESPTOOLPY_MONITOR_BAUD_OTHER
#define CONFIG_ESPTOOLPY_MONITOR_BAUD_OTHER_VAL 115200
#define CONFIG_ESPTOOLPY_MONITOR_BAUD 115200
// end of Serial flasher config


// Partition Table

#define CONFIG_PARTITION_TABLE_SINGLE_APP 1
// #define CONFIG_PARTITION_TABLE_SINGLE_APP_LARGE
// #define CONFIG_PARTITION_TABLE_TWO_OTA
// #define CONFIG_PARTITION_TABLE_CUSTOM
#define CONFIG_PARTITION_TABLE_CUSTOM_FILENAME "partitions.csv"
#define CONFIG_PARTITION_TABLE_FILENAME "partitions_singleapp_coredump.csv"
#define CONFIG_PARTITION_TABLE_OFFSET 0x8000
#define CONFIG_PARTITION_TABLE_MD5 1
// end of Partition Table

#define CONFIG_LIB_BUILDER_FLASHMODE "qio"
#define CONFIG_LIB_BUILDER_FLASHFREQ "80m"
#define CONFIG_LIB_BUILDER_COMPILE 1


// ESP RainMaker Config

// #define CONFIG_ESP_RMAKER_NO_CLAIM
#define CONFIG_ESP_RMAKER_SELF_CLAIM 1
// #define CONFIG_ESP_RMAKER_ASSISTED_CLAIM
#define CONFIG_ESP_RMAKER_USE_NVS 1
#define CONFIG_ESP_RMAKER_CLAIM_TYPE 1
#define CONFIG_ESP_RMAKER_CLAIM_SERVICE_BASE_URL "https://esp-claiming.rainmaker.espressif.com"
// #define CONFIG_ESP_RMAKER_READ_MQTT_HOST_FROM_CONFIG
// #define CONFIG_ESP_RMAKER_READ_NODE_ID_FROM_CERT_CN
#define CONFIG_ESP_RMAKER_MQTT_HOST "a1p72mufdu6064-ats.iot.us-east-1.amazonaws.com"
#define CONFIG_ESP_RMAKER_MQTT_USE_BASIC_INGEST_TOPICS 1
#define CONFIG_ESP_RMAKER_MQTT_ENABLE_BUDGETING 1
#define CONFIG_ESP_RMAKER_MQTT_DEFAULT_BUDGET 100
#define CONFIG_ESP_RMAKER_MQTT_MAX_BUDGET 1024
#define CONFIG_ESP_RMAKER_MQTT_BUDGET_REVIVE_PERIOD 5
#define CONFIG_ESP_RMAKER_MQTT_BUDGET_REVIVE_COUNT 1
#define CONFIG_ESP_RMAKER_MAX_PARAM_DATA_SIZE 1024
// #define CONFIG_ESP_RMAKER_DISABLE_USER_MAPPING_PROV
#define CONFIG_ESP_RMAKER_USER_ID_CHECK 1
// #define CONFIG_RMAKER_NAME_PARAM_CB
// #define CONFIG_ESP_RMAKER_LOCAL_CTRL_FEATURE_ENABLE
// #define CONFIG_ESP_RMAKER_LOCAL_CTRL_AUTO_ENABLE
#define CONFIG_ESP_RMAKER_CONSOLE_UART_NUM_0 1
// #define CONFIG_ESP_RMAKER_CONSOLE_UART_NUM_1
#define CONFIG_ESP_RMAKER_CONSOLE_UART_NUM 0
#define CONFIG_ESP_RMAKER_USE_CERT_BUNDLE 1


// ESP RainMaker OTA Config

#define CONFIG_ESP_RMAKER_OTA_AUTOFETCH 1
#define CONFIG_ESP_RMAKER_OTA_AUTOFETCH_PERIOD 0
// #define CONFIG_ESP_RMAKER_SKIP_COMMON_NAME_CHECK
#define CONFIG_ESP_RMAKER_SKIP_VERSION_CHECK 1
// #define CONFIG_ESP_RMAKER_SKIP_SECURE_VERSION_CHECK
// #define CONFIG_ESP_RMAKER_SKIP_PROJECT_NAME_CHECK
#define CONFIG_ESP_RMAKER_OTA_HTTP_RX_BUFFER_SIZE 1024
#define CONFIG_ESP_RMAKER_OTA_ROLLBACK_WAIT_PERIOD 90
// #define CONFIG_ESP_RMAKER_OTA_DISABLE_AUTO_REBOOT
#define CONFIG_ESP_RMAKER_OTA_TIME_SUPPORT 1
// end of ESP RainMaker OTA Config


// ESP RainMaker Scheduling

#define CONFIG_ESP_RMAKER_SCHEDULING_MAX_SCHEDULES 10
// end of ESP RainMaker Scheduling


// ESP RainMaker Scenes

#define CONFIG_ESP_RMAKER_SCENES_MAX_SCENES 10
// #define CONFIG_ESP_RMAKER_SCENES_DEACTIVATE_SUPPORT
// end of ESP RainMaker Scenes


// ESP RainMaker Command-Response

#define CONFIG_ESP_RMAKER_CMD_RESP_ENABLE 1
// #define CONFIG_ESP_RMAKER_CMD_RESP_TEST_ENABLE
// end of ESP RainMaker Command-Response
// end of ESP RainMaker Config


// Arduino Configuration

#define CONFIG_ARDUINO_VARIANT "esp32s3"
#define CONFIG_ENABLE_ARDUINO_DEPENDS 1
#define CONFIG_AUTOSTART_ARDUINO 1
// #define CONFIG_ARDUINO_RUN_CORE0
#define CONFIG_ARDUINO_RUN_CORE1 1
// #define CONFIG_ARDUINO_RUN_NO_AFFINITY
#define CONFIG_ARDUINO_RUNNING_CORE 1
#define CONFIG_ARDUINO_LOOP_STACK_SIZE 8192
// #define CONFIG_ARDUINO_EVENT_RUN_CORE0
#define CONFIG_ARDUINO_EVENT_RUN_CORE1 1
// #define CONFIG_ARDUINO_EVENT_RUN_NO_AFFINITY
#define CONFIG_ARDUINO_EVENT_RUNNING_CORE 1
// #define CONFIG_ARDUINO_SERIAL_EVENT_RUN_CORE0
// #define CONFIG_ARDUINO_SERIAL_EVENT_RUN_CORE1
#define CONFIG_ARDUINO_SERIAL_EVENT_RUN_NO_AFFINITY 1
#define CONFIG_ARDUINO_SERIAL_EVENT_TASK_RUNNING_CORE -1
#define CONFIG_ARDUINO_SERIAL_EVENT_TASK_STACK_SIZE 2048
#define CONFIG_ARDUINO_SERIAL_EVENT_TASK_PRIORITY 24
#define CONFIG_ARDUINO_UDP_RUN_CORE0 1
// #define CONFIG_ARDUINO_UDP_RUN_CORE1
// #define CONFIG_ARDUINO_UDP_RUN_NO_AFFINITY
#define CONFIG_ARDUINO_UDP_RUNNING_CORE 0
#define CONFIG_ARDUINO_UDP_TASK_PRIORITY 3
// #define CONFIG_ARDUINO_ISR_IRAM
// #define CONFIG_DISABLE_HAL_LOCKS


// Debug Log Configuration

// #define CONFIG_ARDUHAL_LOG_DEFAULT_LEVEL_NONE
#define CONFIG_ARDUHAL_LOG_DEFAULT_LEVEL_ERROR 1
// #define CONFIG_ARDUHAL_LOG_DEFAULT_LEVEL_WARN
// #define CONFIG_ARDUHAL_LOG_DEFAULT_LEVEL_INFO
// #define CONFIG_ARDUHAL_LOG_DEFAULT_LEVEL_DEBUG
// #define CONFIG_ARDUHAL_LOG_DEFAULT_LEVEL_VERBOSE
#define CONFIG_ARDUHAL_LOG_DEFAULT_LEVEL 1
// #define CONFIG_ARDUHAL_LOG_COLORS
#define CONFIG_ARDUHAL_ESP_LOG 1
// end of Debug Log Configuration

#define CONFIG_ARDUHAL_PARTITION_SCHEME_DEFAULT 1
// #define CONFIG_ARDUHAL_PARTITION_SCHEME_MINIMAL
// #define CONFIG_ARDUHAL_PARTITION_SCHEME_NO_OTA
// #define CONFIG_ARDUHAL_PARTITION_SCHEME_HUGE_APP
// #define CONFIG_ARDUHAL_PARTITION_SCHEME_MIN_SPIFFS
#define CONFIG_ARDUHAL_PARTITION_SCHEME "default"
// #define CONFIG_AUTOCONNECT_WIFI
// #define CONFIG_ARDUINO_SELECTIVE_COMPILATION
// end of Arduino Configuration


// Arduino TinyUSB

#define CONFIG_TINYUSB_ENABLED 1


// Serial (CDC) driver

#define CONFIG_TINYUSB_CDC_ENABLED 1
#define CONFIG_TINYUSB_DESC_CDC_STRING "Espressif CDC Device"
#define CONFIG_TINYUSB_CDC_RX_BUFSIZE 64
#define CONFIG_TINYUSB_CDC_TX_BUFSIZE 64
// end of Serial (CDC) driver


// Mass Storage (MSC) driver

#define CONFIG_TINYUSB_MSC_ENABLED 1
#define CONFIG_TINYUSB_DESC_MSC_STRING "Espressif MSC Device"
#define CONFIG_TINYUSB_MSC_BUFSIZE 4096
// end of Mass Storage (MSC) driver


// Human Interface (HID) driver

#define CONFIG_TINYUSB_HID_ENABLED 1
#define CONFIG_TINYUSB_DESC_HID_STRING "Espressif HID Device"
#define CONFIG_TINYUSB_HID_BUFSIZE 64
// end of Human Interface (HID) driver


// MIDI driver

#define CONFIG_TINYUSB_MIDI_ENABLED 1
#define CONFIG_TINYUSB_DESC_MIDI_STRING "Espressif MIDI Device"
#define CONFIG_TINYUSB_MIDI_RX_BUFSIZE 64
#define CONFIG_TINYUSB_MIDI_TX_BUFSIZE 64
// end of MIDI driver


// VIDEO driver

#define CONFIG_TINYUSB_VIDEO_ENABLED 1
#define CONFIG_TINYUSB_DESC_VIDEO_STRING "Espressif VIDEO Device"
#define CONFIG_TINYUSB_VIDEO_STREAMING_BUFSIZE 64
#define CONFIG_TINYUSB_VIDEO_STREAMING_IFS 1
// end of VIDEO driver


// DFU Runtime driver

#define CONFIG_TINYUSB_DFU_RT_ENABLED 1
#define CONFIG_TINYUSB_DESC_DFU_RT_STRING "Espressif DFU_RT Device"
// end of DFU Runtime driver


// DFU driver

#define CONFIG_TINYUSB_DFU_ENABLED 1
#define CONFIG_TINYUSB_DESC_DFU_STRING "Espressif DFU Device"
#define CONFIG_TINYUSB_DFU_BUFSIZE 4096
// end of DFU driver

#
// VENDOR driver
#
#define CONFIG_TINYUSB_VENDOR_ENABLED 1
#define CONFIG_TINYUSB_DESC_VENDOR_STRING "Espressif VENDOR Device"
#define CONFIG_TINYUSB_VENDOR_RX_BUFSIZE 64
#define CONFIG_TINYUSB_VENDOR_TX_BUFSIZE 64
// end of VENDOR driver

#define CONFIG_TINYUSB_DEBUG_LEVEL 0
// end of Arduino TinyUSB

#
// Compiler options
#
// #define CONFIG_COMPILER_OPTIMIZATION_DEFAULT
#define CONFIG_COMPILER_OPTIMIZATION_SIZE 1
// #define CONFIG_COMPILER_OPTIMIZATION_PERF
// #define CONFIG_COMPILER_OPTIMIZATION_NONE
#define CONFIG_COMPILER_OPTIMIZATION_ASSERTIONS_ENABLE 1
// #define CONFIG_COMPILER_OPTIMIZATION_ASSERTIONS_SILENT
// #define CONFIG_COMPILER_OPTIMIZATION_ASSERTIONS_DISABLE
#define CONFIG_COMPILER_OPTIMIZATION_ASSERTION_LEVEL 2
// #define CONFIG_COMPILER_OPTIMIZATION_CHECKS_SILENT
#define CONFIG_COMPILER_HIDE_PATHS_MACROS 1
#define CONFIG_COMPILER_CXX_EXCEPTIONS 1
#define CONFIG_COMPILER_CXX_EXCEPTIONS_EMG_POOL_SIZE 0
// #define CONFIG_COMPILER_CXX_RTTI
// #define CONFIG_COMPILER_STACK_CHECK_MODE_NONE
#define CONFIG_COMPILER_STACK_CHECK_MODE_NORM 1
// #define CONFIG_COMPILER_STACK_CHECK_MODE_STRONG
// #define CONFIG_COMPILER_STACK_CHECK_MODE_ALL
#define CONFIG_COMPILER_STACK_CHECK 1
#define CONFIG_COMPILER_WARN_WRITE_STRINGS 1
// #define CONFIG_COMPILER_DISABLE_GCC8_WARNINGS
// #define CONFIG_COMPILER_DUMP_RTL_FILES
// end of Compiler options


// Component config



// Application Level Tracing

// #define CONFIG_APPTRACE_DEST_JTAG
#define CONFIG_APPTRACE_DEST_NONE 1
#define CONFIG_APPTRACE_LOCK_ENABLE 1
// end of Application Level Tracing


// ESP-ASIO

// #define CONFIG_ASIO_SSL_SUPPORT
// end of ESP-ASIO


// Bluetooth

#define CONFIG_BT_ENABLED 1
#define CONFIG_BT_SOC_SUPPORT_5_0 1


// Bluetooth controller

#define CONFIG_BT_CTRL_MODE_EFF 1
#define CONFIG_BT_CTRL_BLE_MAX_ACT 6
#define CONFIG_BT_CTRL_BLE_MAX_ACT_EFF 6
#define CONFIG_BT_CTRL_BLE_STATIC_ACL_TX_BUF_NB 0
#define CONFIG_BT_CTRL_PINNED_TO_CORE_0 1
// #define CONFIG_BT_CTRL_PINNED_TO_CORE_1
#define CONFIG_BT_CTRL_PINNED_TO_CORE 0
#define CONFIG_BT_CTRL_HCI_MODE_VHCI 1
// #define CONFIG_BT_CTRL_HCI_MODE_UART_H4
#define CONFIG_BT_CTRL_HCI_TL 1
#define CONFIG_BT_CTRL_ADV_DUP_FILT_MAX 30
#define CONFIG_BT_BLE_CCA_MODE_NONE 1
// #define CONFIG_BT_BLE_CCA_MODE_HW
// #define CONFIG_BT_BLE_CCA_MODE_SW
#define CONFIG_BT_BLE_CCA_MODE 0
#define CONFIG_BT_CTRL_HW_CCA_VAL 20
#define CONFIG_BT_CTRL_HW_CCA_EFF 0
#define CONFIG_BT_CTRL_CE_LENGTH_TYPE_ORIG 1
// #define CONFIG_BT_CTRL_CE_LENGTH_TYPE_CE
// #define CONFIG_BT_CTRL_CE_LENGTH_TYPE_SD
#define CONFIG_BT_CTRL_CE_LENGTH_TYPE_EFF 0
#define CONFIG_BT_CTRL_TX_ANTENNA_INDEX_0 1
// #define CONFIG_BT_CTRL_TX_ANTENNA_INDEX_1
#define CONFIG_BT_CTRL_TX_ANTENNA_INDEX_EFF 0
#define CONFIG_BT_CTRL_RX_ANTENNA_INDEX_0 1
// #define CONFIG_BT_CTRL_RX_ANTENNA_INDEX_1
#define CONFIG_BT_CTRL_RX_ANTENNA_INDEX_EFF 0
// #define CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_N24
// #define CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_N21
// #define CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_N18
// #define CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_N15
// #define CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_N12
// #define CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_N9
// #define CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_N6
// #define CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_N3
// #define CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_N0
// #define CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_P3
// #define CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_P6
#define CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_P9 1
// #define CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_P12
// #define CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_P15
// #define CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_P18
// #define CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_P21
#define CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_EFF 11
#define CONFIG_BT_CTRL_BLE_ADV_REPORT_FLOW_CTRL_SUPP 1
#define CONFIG_BT_CTRL_BLE_ADV_REPORT_FLOW_CTRL_NUM 100
#define CONFIG_BT_CTRL_BLE_ADV_REPORT_DISCARD_THRSHOLD 20
#define CONFIG_BT_CTRL_BLE_SCAN_DUPL 1
#define CONFIG_BT_CTRL_SCAN_DUPL_TYPE_DEVICE 1
// #define CONFIG_BT_CTRL_SCAN_DUPL_TYPE_DATA
// #define CONFIG_BT_CTRL_SCAN_DUPL_TYPE_DATA_DEVICE
#define CONFIG_BT_CTRL_SCAN_DUPL_TYPE 0
#define CONFIG_BT_CTRL_SCAN_DUPL_CACHE_SIZE 100
#define CONFIG_BT_CTRL_DUPL_SCAN_CACHE_REFRESH_PERIOD 0
// #define CONFIG_BT_CTRL_BLE_MESH_SCAN_DUPL_EN
// #define CONFIG_BT_CTRL_COEX_PHY_CODED_TX_RX_TLIM_EN
#define CONFIG_BT_CTRL_COEX_PHY_CODED_TX_RX_TLIM_DIS 1
#define CONFIG_BT_CTRL_COEX_PHY_CODED_TX_RX_TLIM_EFF 0


// MODEM SLEEP Options

// #define CONFIG_BT_CTRL_MODEM_SLEEP
// end of MODEM SLEEP Options

#define CONFIG_BT_CTRL_SLEEP_MODE_EFF 0
#define CONFIG_BT_CTRL_SLEEP_CLOCK_EFF 0
#define CONFIG_BT_CTRL_HCI_TL_EFF 1
// #define CONFIG_BT_CTRL_AGC_RECORRECT_EN
// #define CONFIG_BT_CTRL_SCAN_BACKOFF_UPPERLIMITMAX
// #define CONFIG_BT_BLE_ADV_DATA_LENGTH_ZERO_AUX
// end of Bluetooth controller

#define CONFIG_BT_BLUEDROID_ENABLED 1
// #define CONFIG_BT_NIMBLE_ENABLED
// #define CONFIG_BT_CONTROLLER_ONLY


// Bluedroid Options

#define CONFIG_BT_BTC_TASK_STACK_SIZE 3072
#define CONFIG_BT_BLUEDROID_PINNED_TO_CORE_0 1
// #define CONFIG_BT_BLUEDROID_PINNED_TO_CORE_1
#define CONFIG_BT_BLUEDROID_PINNED_TO_CORE 0
#define CONFIG_BT_BTU_TASK_STACK_SIZE 4352
// #define CONFIG_BT_BLUEDROID_MEM_DEBUG
#define CONFIG_BT_BLE_ENABLED 1
#define CONFIG_BT_GATTS_ENABLE 1
// #define CONFIG_BT_GATTS_PPCP_CHAR_GAP
// #define CONFIG_BT_BLE_BLUFI_ENABLE
#define CONFIG_BT_GATT_MAX_SR_PROFILES 8
#define CONFIG_BT_GATT_MAX_SR_ATTRIBUTES 100
// #define CONFIG_BT_GATTS_SEND_SERVICE_CHANGE_MANUAL
#define CONFIG_BT_GATTS_SEND_SERVICE_CHANGE_AUTO 1
#define CONFIG_BT_GATTS_SEND_SERVICE_CHANGE_MODE 0
// #define CONFIG_BT_GATTS_ROBUST_CACHING_ENABLED
// #define CONFIG_BT_GATTS_DEVICE_NAME_WRITABLE
// #define CONFIG_BT_GATTS_APPEARANCE_WRITABLE
#define CONFIG_BT_GATTC_ENABLE 1
#define CONFIG_BT_GATTC_MAX_CACHE_CHAR 40
#define CONFIG_BT_GATTC_NOTIF_REG_MAX 5
// #define CONFIG_BT_GATTC_CACHE_NVS_FLASH
#define CONFIG_BT_GATTC_CONNECT_RETRY_COUNT 3
#define CONFIG_BT_BLE_SMP_ENABLE 1
// #define CONFIG_BT_SMP_SLAVE_CON_PARAMS_UPD_ENABLE
// #define CONFIG_BT_STACK_NO_LOG


// BT DEBUG LOG LEVEL

// #define CONFIG_BT_LOG_HCI_TRACE_LEVEL_NONE
// #define CONFIG_BT_LOG_HCI_TRACE_LEVEL_ERROR
#define CONFIG_BT_LOG_HCI_TRACE_LEVEL_WARNING 1
// #define CONFIG_BT_LOG_HCI_TRACE_LEVEL_API
// #define CONFIG_BT_LOG_HCI_TRACE_LEVEL_EVENT
// #define CONFIG_BT_LOG_HCI_TRACE_LEVEL_DEBUG
// #define CONFIG_BT_LOG_HCI_TRACE_LEVEL_VERBOSE
#define CONFIG_BT_LOG_HCI_TRACE_LEVEL 2
// #define CONFIG_BT_LOG_BTM_TRACE_LEVEL_NONE
// #define CONFIG_BT_LOG_BTM_TRACE_LEVEL_ERROR
#define CONFIG_BT_LOG_BTM_TRACE_LEVEL_WARNING 1
// #define CONFIG_BT_LOG_BTM_TRACE_LEVEL_API
// #define CONFIG_BT_LOG_BTM_TRACE_LEVEL_EVENT
// #define CONFIG_BT_LOG_BTM_TRACE_LEVEL_DEBUG
// #define CONFIG_BT_LOG_BTM_TRACE_LEVEL_VERBOSE
#define CONFIG_BT_LOG_BTM_TRACE_LEVEL 2
// #define CONFIG_BT_LOG_L2CAP_TRACE_LEVEL_NONE
// #define CONFIG_BT_LOG_L2CAP_TRACE_LEVEL_ERROR
#define CONFIG_BT_LOG_L2CAP_TRACE_LEVEL_WARNING 1
// #define CONFIG_BT_LOG_L2CAP_TRACE_LEVEL_API
// #define CONFIG_BT_LOG_L2CAP_TRACE_LEVEL_EVENT
// #define CONFIG_BT_LOG_L2CAP_TRACE_LEVEL_DEBUG
// #define CONFIG_BT_LOG_L2CAP_TRACE_LEVEL_VERBOSE
#define CONFIG_BT_LOG_L2CAP_TRACE_LEVEL 2
// #define CONFIG_BT_LOG_RFCOMM_TRACE_LEVEL_NONE
// #define CONFIG_BT_LOG_RFCOMM_TRACE_LEVEL_ERROR
#define CONFIG_BT_LOG_RFCOMM_TRACE_LEVEL_WARNING 1
// #define CONFIG_BT_LOG_RFCOMM_TRACE_LEVEL_API
// #define CONFIG_BT_LOG_RFCOMM_TRACE_LEVEL_EVENT
// #define CONFIG_BT_LOG_RFCOMM_TRACE_LEVEL_DEBUG
// #define CONFIG_BT_LOG_RFCOMM_TRACE_LEVEL_VERBOSE
#define CONFIG_BT_LOG_RFCOMM_TRACE_LEVEL 2
// #define CONFIG_BT_LOG_SDP_TRACE_LEVEL_NONE
// #define CONFIG_BT_LOG_SDP_TRACE_LEVEL_ERROR
#define CONFIG_BT_LOG_SDP_TRACE_LEVEL_WARNING 1
// #define CONFIG_BT_LOG_SDP_TRACE_LEVEL_API
// #define CONFIG_BT_LOG_SDP_TRACE_LEVEL_EVENT
// #define CONFIG_BT_LOG_SDP_TRACE_LEVEL_DEBUG
// #define CONFIG_BT_LOG_SDP_TRACE_LEVEL_VERBOSE
#define CONFIG_BT_LOG_SDP_TRACE_LEVEL 2
// #define CONFIG_BT_LOG_GAP_TRACE_LEVEL_NONE
// #define CONFIG_BT_LOG_GAP_TRACE_LEVEL_ERROR
#define CONFIG_BT_LOG_GAP_TRACE_LEVEL_WARNING 1
// #define CONFIG_BT_LOG_GAP_TRACE_LEVEL_API
// #define CONFIG_BT_LOG_GAP_TRACE_LEVEL_EVENT
// #define CONFIG_BT_LOG_GAP_TRACE_LEVEL_DEBUG
// #define CONFIG_BT_LOG_GAP_TRACE_LEVEL_VERBOSE
#define CONFIG_BT_LOG_GAP_TRACE_LEVEL 2
// #define CONFIG_BT_LOG_BNEP_TRACE_LEVEL_NONE
// #define CONFIG_BT_LOG_BNEP_TRACE_LEVEL_ERROR
#define CONFIG_BT_LOG_BNEP_TRACE_LEVEL_WARNING 1
// #define CONFIG_BT_LOG_BNEP_TRACE_LEVEL_API
// #define CONFIG_BT_LOG_BNEP_TRACE_LEVEL_EVENT
// #define CONFIG_BT_LOG_BNEP_TRACE_LEVEL_DEBUG
// #define CONFIG_BT_LOG_BNEP_TRACE_LEVEL_VERBOSE
#define CONFIG_BT_LOG_BNEP_TRACE_LEVEL 2
// #define CONFIG_BT_LOG_PAN_TRACE_LEVEL_NONE
// #define CONFIG_BT_LOG_PAN_TRACE_LEVEL_ERROR
#define CONFIG_BT_LOG_PAN_TRACE_LEVEL_WARNING 1
// #define CONFIG_BT_LOG_PAN_TRACE_LEVEL_API
// #define CONFIG_BT_LOG_PAN_TRACE_LEVEL_EVENT
// #define CONFIG_BT_LOG_PAN_TRACE_LEVEL_DEBUG
// #define CONFIG_BT_LOG_PAN_TRACE_LEVEL_VERBOSE
#define CONFIG_BT_LOG_PAN_TRACE_LEVEL 2
// #define CONFIG_BT_LOG_A2D_TRACE_LEVEL_NONE
// #define CONFIG_BT_LOG_A2D_TRACE_LEVEL_ERROR
#define CONFIG_BT_LOG_A2D_TRACE_LEVEL_WARNING 1
// #define CONFIG_BT_LOG_A2D_TRACE_LEVEL_API
// #define CONFIG_BT_LOG_A2D_TRACE_LEVEL_EVENT
// #define CONFIG_BT_LOG_A2D_TRACE_LEVEL_DEBUG
// #define CONFIG_BT_LOG_A2D_TRACE_LEVEL_VERBOSE
#define CONFIG_BT_LOG_A2D_TRACE_LEVEL 2
// #define CONFIG_BT_LOG_AVDT_TRACE_LEVEL_NONE
// #define CONFIG_BT_LOG_AVDT_TRACE_LEVEL_ERROR
#define CONFIG_BT_LOG_AVDT_TRACE_LEVEL_WARNING 1
// #define CONFIG_BT_LOG_AVDT_TRACE_LEVEL_API
// #define CONFIG_BT_LOG_AVDT_TRACE_LEVEL_EVENT
// #define CONFIG_BT_LOG_AVDT_TRACE_LEVEL_DEBUG
// #define CONFIG_BT_LOG_AVDT_TRACE_LEVEL_VERBOSE
#define CONFIG_BT_LOG_AVDT_TRACE_LEVEL 2
// #define CONFIG_BT_LOG_AVCT_TRACE_LEVEL_NONE
// #define CONFIG_BT_LOG_AVCT_TRACE_LEVEL_ERROR
#define CONFIG_BT_LOG_AVCT_TRACE_LEVEL_WARNING 1
// #define CONFIG_BT_LOG_AVCT_TRACE_LEVEL_API
// #define CONFIG_BT_LOG_AVCT_TRACE_LEVEL_EVENT
// #define CONFIG_BT_LOG_AVCT_TRACE_LEVEL_DEBUG
// #define CONFIG_BT_LOG_AVCT_TRACE_LEVEL_VERBOSE
#define CONFIG_BT_LOG_AVCT_TRACE_LEVEL 2
// #define CONFIG_BT_LOG_AVRC_TRACE_LEVEL_NONE
// #define CONFIG_BT_LOG_AVRC_TRACE_LEVEL_ERROR
#define CONFIG_BT_LOG_AVRC_TRACE_LEVEL_WARNING 1
// #define CONFIG_BT_LOG_AVRC_TRACE_LEVEL_API
// #define CONFIG_BT_LOG_AVRC_TRACE_LEVEL_EVENT
// #define CONFIG_BT_LOG_AVRC_TRACE_LEVEL_DEBUG
// #define CONFIG_BT_LOG_AVRC_TRACE_LEVEL_VERBOSE
#define CONFIG_BT_LOG_AVRC_TRACE_LEVEL 2
// #define CONFIG_BT_LOG_MCA_TRACE_LEVEL_NONE
// #define CONFIG_BT_LOG_MCA_TRACE_LEVEL_ERROR
#define CONFIG_BT_LOG_MCA_TRACE_LEVEL_WARNING 1
// #define CONFIG_BT_LOG_MCA_TRACE_LEVEL_API
// #define CONFIG_BT_LOG_MCA_TRACE_LEVEL_EVENT
// #define CONFIG_BT_LOG_MCA_TRACE_LEVEL_DEBUG
// #define CONFIG_BT_LOG_MCA_TRACE_LEVEL_VERBOSE
#define CONFIG_BT_LOG_MCA_TRACE_LEVEL 2
// #define CONFIG_BT_LOG_HID_TRACE_LEVEL_NONE
// #define CONFIG_BT_LOG_HID_TRACE_LEVEL_ERROR
#define CONFIG_BT_LOG_HID_TRACE_LEVEL_WARNING 1
// #define CONFIG_BT_LOG_HID_TRACE_LEVEL_API
// #define CONFIG_BT_LOG_HID_TRACE_LEVEL_EVENT
// #define CONFIG_BT_LOG_HID_TRACE_LEVEL_DEBUG
// #define CONFIG_BT_LOG_HID_TRACE_LEVEL_VERBOSE
#define CONFIG_BT_LOG_HID_TRACE_LEVEL 2
// #define CONFIG_BT_LOG_APPL_TRACE_LEVEL_NONE
// #define CONFIG_BT_LOG_APPL_TRACE_LEVEL_ERROR
#define CONFIG_BT_LOG_APPL_TRACE_LEVEL_WARNING 1
// #define CONFIG_BT_LOG_APPL_TRACE_LEVEL_API
// #define CONFIG_BT_LOG_APPL_TRACE_LEVEL_EVENT
// #define CONFIG_BT_LOG_APPL_TRACE_LEVEL_DEBUG
// #define CONFIG_BT_LOG_APPL_TRACE_LEVEL_VERBOSE
#define CONFIG_BT_LOG_APPL_TRACE_LEVEL 2
// #define CONFIG_BT_LOG_GATT_TRACE_LEVEL_NONE
// #define CONFIG_BT_LOG_GATT_TRACE_LEVEL_ERROR
#define CONFIG_BT_LOG_GATT_TRACE_LEVEL_WARNING 1
// #define CONFIG_BT_LOG_GATT_TRACE_LEVEL_API
// #define CONFIG_BT_LOG_GATT_TRACE_LEVEL_EVENT
// #define CONFIG_BT_LOG_GATT_TRACE_LEVEL_DEBUG
// #define CONFIG_BT_LOG_GATT_TRACE_LEVEL_VERBOSE
#define CONFIG_BT_LOG_GATT_TRACE_LEVEL 2
// #define CONFIG_BT_LOG_SMP_TRACE_LEVEL_NONE
// #define CONFIG_BT_LOG_SMP_TRACE_LEVEL_ERROR
#define CONFIG_BT_LOG_SMP_TRACE_LEVEL_WARNING 1
// #define CONFIG_BT_LOG_SMP_TRACE_LEVEL_API
// #define CONFIG_BT_LOG_SMP_TRACE_LEVEL_EVENT
// #define CONFIG_BT_LOG_SMP_TRACE_LEVEL_DEBUG
// #define CONFIG_BT_LOG_SMP_TRACE_LEVEL_VERBOSE
#define CONFIG_BT_LOG_SMP_TRACE_LEVEL 2
// #define CONFIG_BT_LOG_BTIF_TRACE_LEVEL_NONE
// #define CONFIG_BT_LOG_BTIF_TRACE_LEVEL_ERROR
#define CONFIG_BT_LOG_BTIF_TRACE_LEVEL_WARNING 1
// #define CONFIG_BT_LOG_BTIF_TRACE_LEVEL_API
// #define CONFIG_BT_LOG_BTIF_TRACE_LEVEL_EVENT
// #define CONFIG_BT_LOG_BTIF_TRACE_LEVEL_DEBUG
// #define CONFIG_BT_LOG_BTIF_TRACE_LEVEL_VERBOSE
#define CONFIG_BT_LOG_BTIF_TRACE_LEVEL 2
// #define CONFIG_BT_LOG_BTC_TRACE_LEVEL_NONE
// #define CONFIG_BT_LOG_BTC_TRACE_LEVEL_ERROR
#define CONFIG_BT_LOG_BTC_TRACE_LEVEL_WARNING 1
// #define CONFIG_BT_LOG_BTC_TRACE_LEVEL_API
// #define CONFIG_BT_LOG_BTC_TRACE_LEVEL_EVENT
// #define CONFIG_BT_LOG_BTC_TRACE_LEVEL_DEBUG
// #define CONFIG_BT_LOG_BTC_TRACE_LEVEL_VERBOSE
#define CONFIG_BT_LOG_BTC_TRACE_LEVEL 2
// #define CONFIG_BT_LOG_OSI_TRACE_LEVEL_NONE
// #define CONFIG_BT_LOG_OSI_TRACE_LEVEL_ERROR
#define CONFIG_BT_LOG_OSI_TRACE_LEVEL_WARNING 1
// #define CONFIG_BT_LOG_OSI_TRACE_LEVEL_API
// #define CONFIG_BT_LOG_OSI_TRACE_LEVEL_EVENT
// #define CONFIG_BT_LOG_OSI_TRACE_LEVEL_DEBUG
// #define CONFIG_BT_LOG_OSI_TRACE_LEVEL_VERBOSE
#define CONFIG_BT_LOG_OSI_TRACE_LEVEL 2
// #define CONFIG_BT_LOG_BLUFI_TRACE_LEVEL_NONE
// #define CONFIG_BT_LOG_BLUFI_TRACE_LEVEL_ERROR
#define CONFIG_BT_LOG_BLUFI_TRACE_LEVEL_WARNING 1
// #define CONFIG_BT_LOG_BLUFI_TRACE_LEVEL_API
// #define CONFIG_BT_LOG_BLUFI_TRACE_LEVEL_EVENT
// #define CONFIG_BT_LOG_BLUFI_TRACE_LEVEL_DEBUG
// #define CONFIG_BT_LOG_BLUFI_TRACE_LEVEL_VERBOSE
#define CONFIG_BT_LOG_BLUFI_TRACE_LEVEL 2
// end of BT DEBUG LOG LEVEL

#define CONFIG_BT_ACL_CONNECTIONS 4
#define CONFIG_BT_MULTI_CONNECTION_ENBALE 1
// #define CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST
// #define CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY
// #define CONFIG_BT_BLE_HOST_QUEUE_CONG_CHECK
#define CONFIG_BT_SMP_ENABLE 1
#define CONFIG_BT_SMP_MAX_BONDS 15
// #define CONFIG_BT_BLE_ACT_SCAN_REP_ADV_SCAN
#define CONFIG_BT_BLE_ESTAB_LINK_CONN_TOUT 30
#define CONFIG_BT_MAX_DEVICE_NAME_LEN 32
#define CONFIG_BT_BLE_RPA_TIMEOUT 900
#define CONFIG_BT_BLE_50_FEATURES_SUPPORTED 1
#define CONFIG_BT_BLE_42_FEATURES_SUPPORTED 1
// #define CONFIG_BT_BLE_HIGH_DUTY_ADV_INTERVAL
// end of Bluedroid Options
// end of Bluetooth

#define CONFIG_BLE_MESH 1
#define CONFIG_BLE_MESH_HCI_5_0 1
// #define CONFIG_BLE_MESH_RANDOM_ADV_INTERVAL
#define CONFIG_BLE_MESH_USE_DUPLICATE_SCAN 1
#define CONFIG_BLE_MESH_MEM_ALLOC_MODE_INTERNAL 1
// #define CONFIG_BLE_MESH_MEM_ALLOC_MODE_EXTERNAL
// #define CONFIG_BLE_MESH_MEM_ALLOC_MODE_DEFAULT
#define CONFIG_BLE_MESH_DEINIT 1


// BLE Mesh and BLE coexistence support

// #define CONFIG_BLE_MESH_SUPPORT_BLE_ADV
// #define CONFIG_BLE_MESH_SUPPORT_BLE_SCAN
// end of BLE Mesh and BLE coexistence support

// #define CONFIG_BLE_MESH_FAST_PROV
// #define CONFIG_BLE_MESH_NODE
// #define CONFIG_BLE_MESH_PROVISIONER
#define CONFIG_BLE_MESH_PROV 1
#define CONFIG_BLE_MESH_PB_ADV 1
// #define CONFIG_BLE_MESH_PB_GATT
#define CONFIG_BLE_MESH_PROXY 1
// #define CONFIG_BLE_MESH_GATT_PROXY_CLIENT
#define CONFIG_BLE_MESH_NET_BUF_POOL_USAGE 1
// #define CONFIG_BLE_MESH_SETTINGS
#define CONFIG_BLE_MESH_SUBNET_COUNT 3
#define CONFIG_BLE_MESH_APP_KEY_COUNT 3
#define CONFIG_BLE_MESH_MODEL_KEY_COUNT 3
#define CONFIG_BLE_MESH_MODEL_GROUP_COUNT 3
#define CONFIG_BLE_MESH_LABEL_COUNT 3
#define CONFIG_BLE_MESH_CRPL 10
#define CONFIG_BLE_MESH_MSG_CACHE_SIZE 10
#define CONFIG_BLE_MESH_ADV_BUF_COUNT 60
#define CONFIG_BLE_MESH_IVU_DIVIDER 4
// #define CONFIG_BLE_MESH_IVU_RECOVERY_IVI
#define CONFIG_BLE_MESH_TX_SEG_MSG_COUNT 1
#define CONFIG_BLE_MESH_RX_SEG_MSG_COUNT 1
#define CONFIG_BLE_MESH_RX_SDU_MAX 384
#define CONFIG_BLE_MESH_TX_SEG_MAX 32
// #define CONFIG_BLE_MESH_FRIEND
// #define CONFIG_BLE_MESH_NO_LOG


// BLE Mesh STACK DEBUG LOG LEVEL

// #define CONFIG_BLE_MESH_TRACE_LEVEL_NONE
// #define CONFIG_BLE_MESH_TRACE_LEVEL_ERROR
#define CONFIG_BLE_MESH_TRACE_LEVEL_WARNING 1
// #define CONFIG_BLE_MESH_TRACE_LEVEL_INFO
// #define CONFIG_BLE_MESH_TRACE_LEVEL_DEBUG
// #define CONFIG_BLE_MESH_TRACE_LEVEL_VERBOSE
#define CONFIG_BLE_MESH_STACK_TRACE_LEVEL 2
// end of BLE Mesh STACK DEBUG LOG LEVEL


// BLE Mesh NET BUF DEBUG LOG LEVEL

// #define CONFIG_BLE_MESH_NET_BUF_TRACE_LEVEL_NONE
// #define CONFIG_BLE_MESH_NET_BUF_TRACE_LEVEL_ERROR
#define CONFIG_BLE_MESH_NET_BUF_TRACE_LEVEL_WARNING 1
// #define CONFIG_BLE_MESH_NET_BUF_TRACE_LEVEL_INFO
// #define CONFIG_BLE_MESH_NET_BUF_TRACE_LEVEL_DEBUG
// #define CONFIG_BLE_MESH_NET_BUF_TRACE_LEVEL_VERBOSE
#define CONFIG_BLE_MESH_NET_BUF_TRACE_LEVEL 2
// end of BLE Mesh NET BUF DEBUG LOG LEVEL

#define CONFIG_BLE_MESH_CLIENT_MSG_TIMEOUT 4000


// Support for BLE Mesh Foundation models

// #define CONFIG_BLE_MESH_CFG_CLI
// #define CONFIG_BLE_MESH_HEALTH_CLI
#define CONFIG_BLE_MESH_HEALTH_SRV 1
// end of Support for BLE Mesh Foundation models


// Support for BLE Mesh Client/Server models

// #define CONFIG_BLE_MESH_GENERIC_ONOFF_CLI
// #define CONFIG_BLE_MESH_GENERIC_LEVEL_CLI
// #define CONFIG_BLE_MESH_GENERIC_DEF_TRANS_TIME_CLI
// #define CONFIG_BLE_MESH_GENERIC_POWER_ONOFF_CLI
// #define CONFIG_BLE_MESH_GENERIC_POWER_LEVEL_CLI
// #define CONFIG_BLE_MESH_GENERIC_BATTERY_CLI
// #define CONFIG_BLE_MESH_GENERIC_LOCATION_CLI
// #define CONFIG_BLE_MESH_GENERIC_PROPERTY_CLI
// #define CONFIG_BLE_MESH_SENSOR_CLI
// #define CONFIG_BLE_MESH_TIME_CLI
// #define CONFIG_BLE_MESH_SCENE_CLI
// #define CONFIG_BLE_MESH_SCHEDULER_CLI
// #define CONFIG_BLE_MESH_LIGHT_LIGHTNESS_CLI
// #define CONFIG_BLE_MESH_LIGHT_CTL_CLI
// #define CONFIG_BLE_MESH_LIGHT_HSL_CLI
// #define CONFIG_BLE_MESH_LIGHT_XYL_CLI
// #define CONFIG_BLE_MESH_LIGHT_LC_CLI
#define CONFIG_BLE_MESH_GENERIC_SERVER 1
#define CONFIG_BLE_MESH_SENSOR_SERVER 1
#define CONFIG_BLE_MESH_TIME_SCENE_SERVER 1
#define CONFIG_BLE_MESH_LIGHTING_SERVER 1
// end of Support for BLE Mesh Client/Server models

// #define CONFIG_BLE_MESH_IV_UPDATE_TEST
#define CONFIG_BLE_MESH_DISCARD_OLD_SEQ_AUTH 1


// BLE Mesh specific test option

// #define CONFIG_BLE_MESH_SELF_TEST
// #define CONFIG_BLE_MESH_BQB_TEST
// #define CONFIG_BLE_MESH_SHELL
// #define CONFIG_BLE_MESH_DEBUG
// end of BLE Mesh specific test option

// #define CONFIG_BLE_MESH_EXPERIMENTAL


// CoAP Configuration

#define CONFIG_COAP_MBEDTLS_PSK 1
// #define CONFIG_COAP_MBEDTLS_PKI
// #define CONFIG_COAP_MBEDTLS_DEBUG
#define CONFIG_COAP_LOG_DEFAULT_LEVEL 0
// end of CoAP Configuration


// Driver configurations



// ADC configuration

// #define CONFIG_ADC_FORCE_XPD_FSM
#define CONFIG_ADC_DISABLE_DAC 1
// #define CONFIG_ADC_CONTINUOUS_FORCE_USE_ADC2_ON_C3_S3
// end of ADC configuration


// MCPWM configuration

// #define CONFIG_MCPWM_ISR_IN_IRAM
// end of MCPWM configuration


// SPI configuration

// #define CONFIG_SPI_MASTER_IN_IRAM
// #define CONFIG_SPI_MASTER_ISR_IN_IRAM
// #define CONFIG_SPI_SLAVE_IN_IRAM
// #define CONFIG_SPI_SLAVE_ISR_IN_IRAM
// end of SPI configuration


// TWAI configuration

// #define CONFIG_TWAI_ISR_IN_IRAM
// #define CONFIG_TWAI_ERRATA_FIX_LISTEN_ONLY_DOM
// end of TWAI configuration


// UART configuration

// #define CONFIG_UART_ISR_IN_IRAM
// end of UART configuration


// GDMA Configuration

// #define CONFIG_GDMA_CTRL_FUNC_IN_IRAM
// #define CONFIG_GDMA_ISR_IRAM_SAFE
// end of GDMA Configuration
// end of Driver configurations


// eFuse Bit Manager

// #define CONFIG_EFUSE_CUSTOM_TABLE
// #define CONFIG_EFUSE_VIRTUAL
#define CONFIG_EFUSE_MAX_BLK_LEN 256
// end of eFuse Bit Manager


// ESP-TLS

#define CONFIG_ESP_TLS_USING_MBEDTLS 1
#define CONFIG_ESP_TLS_USE_DS_PERIPHERAL 1
// #define CONFIG_ESP_TLS_CLIENT_SESSION_TICKETS
#define CONFIG_ESP_TLS_SERVER 1
// #define CONFIG_ESP_TLS_SERVER_SESSION_TICKETS
// #define CONFIG_ESP_TLS_SERVER_MIN_AUTH_MODE_OPTIONAL
// #define CONFIG_ESP_TLS_PSK_VERIFICATION
// #define CONFIG_ESP_TLS_INSECURE
// end of ESP-TLS


// ESP32S3-Specific

#define CONFIG_ESP32S3_REV_MIN_0 1
// #define CONFIG_ESP32S3_REV_MIN_1
// #define CONFIG_ESP32S3_REV_MIN_2
#define CONFIG_ESP32S3_REV_MIN_FULL 0
#define CONFIG_ESP_REV_MIN_FULL 0
#define CONFIG_ESP32S3_REV_MAX_FULL_STR_OPT 1
#define CONFIG_ESP32S3_REV_MAX_FULL 99
#define CONFIG_ESP_REV_MAX_FULL 99
// #define CONFIG_ESP32S3_DEFAULT_CPU_FREQ_80
// #define CONFIG_ESP32S3_DEFAULT_CPU_FREQ_160
#define CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240 1
#define CONFIG_ESP32S3_DEFAULT_CPU_FREQ_MHZ 240


// Cache config

#define CONFIG_ESP32S3_INSTRUCTION_CACHE_16KB 1
// #define CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB
#define CONFIG_ESP32S3_INSTRUCTION_CACHE_SIZE 0x4000
// #define CONFIG_ESP32S3_INSTRUCTION_CACHE_4WAYS
#define CONFIG_ESP32S3_INSTRUCTION_CACHE_8WAYS 1
#define CONFIG_ESP32S3_ICACHE_ASSOCIATED_WAYS 8
// #define CONFIG_ESP32S3_INSTRUCTION_CACHE_LINE_16B
#define CONFIG_ESP32S3_INSTRUCTION_CACHE_LINE_32B 1
#define CONFIG_ESP32S3_INSTRUCTION_CACHE_LINE_SIZE 32
// #define CONFIG_ESP32S3_INSTRUCTION_CACHE_WRAP
// #define CONFIG_ESP32S3_DATA_CACHE_16KB
#define CONFIG_ESP32S3_DATA_CACHE_32KB 1
// #define CONFIG_ESP32S3_DATA_CACHE_64KB
#define CONFIG_ESP32S3_DATA_CACHE_SIZE 0x8000
// #define CONFIG_ESP32S3_DATA_CACHE_4WAYS
#define CONFIG_ESP32S3_DATA_CACHE_8WAYS 1
#define CONFIG_ESP32S3_DCACHE_ASSOCIATED_WAYS 8
// #define CONFIG_ESP32S3_DATA_CACHE_LINE_16B
#define CONFIG_ESP32S3_DATA_CACHE_LINE_32B 1
// #define CONFIG_ESP32S3_DATA_CACHE_LINE_64B
#define CONFIG_ESP32S3_DATA_CACHE_LINE_SIZE 32
// #define CONFIG_ESP32S3_DATA_CACHE_WRAP
// end of Cache config

#define CONFIG_ESP32S3_SPIRAM_SUPPORT 1


// SPI RAM config

#define CONFIG_SPIRAM_MODE_QUAD 1
// #define CONFIG_SPIRAM_MODE_OCT
#define CONFIG_SPIRAM_TYPE_AUTO 1
// #define CONFIG_SPIRAM_TYPE_ESPPSRAM16
// #define CONFIG_SPIRAM_TYPE_ESPPSRAM32
// #define CONFIG_SPIRAM_TYPE_ESPPSRAM64
#define CONFIG_SPIRAM_SIZE -1
#define CONFIG_SPIRAM_CLK_IO 30
#define CONFIG_SPIRAM_CS_IO 26
// #define CONFIG_SPIRAM_FETCH_INSTRUCTIONS
// #define CONFIG_SPIRAM_RODATA
// #define CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY
// #define CONFIG_SPIRAM_SPEED_120M
#define CONFIG_SPIRAM_SPEED_80M 1
// #define CONFIG_SPIRAM_SPEED_40M
#define CONFIG_SPIRAM 1
// #define CONFIG_SPIRAM_BOOT_INIT
// #define CONFIG_SPIRAM_USE_MEMMAP
// #define CONFIG_SPIRAM_USE_CAPS_ALLOC
#define CONFIG_SPIRAM_USE_MALLOC 1
#define CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL 4096
#define CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP 1
#define CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL 0
// end of SPI RAM config

// #define CONFIG_ESP32S3_TRAX
#define CONFIG_ESP32S3_TRACEMEM_RESERVE_DRAM 0x0
// #define CONFIG_ESP32S3_ULP_COPROC_ENABLED
#define CONFIG_ESP32S3_ULP_COPROC_RESERVE_MEM 0
#define CONFIG_ESP32S3_DEBUG_OCDAWARE 1
#define CONFIG_ESP32S3_BROWNOUT_DET 1
#define CONFIG_ESP32S3_BROWNOUT_DET_LVL_SEL_7 1
// #define CONFIG_ESP32S3_BROWNOUT_DET_LVL_SEL_6
// #define CONFIG_ESP32S3_BROWNOUT_DET_LVL_SEL_5
// #define CONFIG_ESP32S3_BROWNOUT_DET_LVL_SEL_4
// #define CONFIG_ESP32S3_BROWNOUT_DET_LVL_SEL_3
// #define CONFIG_ESP32S3_BROWNOUT_DET_LVL_SEL_2
// #define CONFIG_ESP32S3_BROWNOUT_DET_LVL_SEL_1
#define CONFIG_ESP32S3_BROWNOUT_DET_LVL 7
#define CONFIG_ESP32S3_TIME_SYSCALL_USE_RTC_FRC1 1
// #define CONFIG_ESP32S3_TIME_SYSCALL_USE_RTC
// #define CONFIG_ESP32S3_TIME_SYSCALL_USE_FRC1
// #define CONFIG_ESP32S3_TIME_SYSCALL_USE_NONE
#define CONFIG_ESP32S3_RTC_CLK_SRC_INT_RC 1
// #define CONFIG_ESP32S3_RTC_CLK_SRC_EXT_CRYS
// #define CONFIG_ESP32S3_RTC_CLK_SRC_EXT_OSC
// #define CONFIG_ESP32S3_RTC_CLK_SRC_INT_8MD256
#define CONFIG_ESP32S3_RTC_CLK_CAL_CYCLES 576
#define CONFIG_ESP32S3_DEEP_SLEEP_WAKEUP_DELAY 2000
// #define CONFIG_ESP32S3_RTCDATA_IN_FAST_MEM
// #define CONFIG_ESP32S3_USE_FIXED_STATIC_RAM_SIZE
// end of ESP32S3-Specific


// ADC-Calibration

// end of ADC-Calibration


// Common ESP-related

#define CONFIG_ESP_ERR_TO_NAME_LOOKUP 1
// end of Common ESP-related


// Ethernet

#define CONFIG_ETH_ENABLED 1
#define CONFIG_ETH_USE_SPI_ETHERNET 1
#define CONFIG_ETH_SPI_ETHERNET_DM9051 1
#define CONFIG_ETH_SPI_ETHERNET_W5500 1
// #define CONFIG_ETH_SPI_ETHERNET_KSZ8851SNL
// #define CONFIG_ETH_USE_OPENETH
// end of Ethernet


// Event Loop Library

// #define CONFIG_ESP_EVENT_LOOP_PROFILING
#define CONFIG_ESP_EVENT_POST_FROM_ISR 1
#define CONFIG_ESP_EVENT_POST_FROM_IRAM_ISR 1
// end of Event Loop Library


// GDB Stub

// end of GDB Stub


// ESP HTTP client

#define CONFIG_ESP_HTTP_CLIENT_ENABLE_HTTPS 1
#define CONFIG_ESP_HTTP_CLIENT_ENABLE_BASIC_AUTH 1
#define CONFIG_ESP_HTTP_CLIENT_ENABLE_DIGEST_AUTH 1
// end of ESP HTTP client


// HTTP Server

#define CONFIG_HTTPD_MAX_REQ_HDR_LEN 1024
#define CONFIG_HTTPD_MAX_URI_LEN 512
#define CONFIG_HTTPD_ERR_RESP_NO_DELAY 1
#define CONFIG_HTTPD_PURGE_BUF_LEN 32
// #define CONFIG_HTTPD_LOG_PURGE_DATA
#define CONFIG_HTTPD_WS_SUPPORT 1
// end of HTTP Server


// ESP HTTPS OTA

// #define CONFIG_OTA_ALLOW_HTTP
// end of ESP HTTPS OTA


// ESP HTTPS server

#define CONFIG_ESP_HTTPS_SERVER_ENABLE 1
// end of ESP HTTPS server


// Hardware Settings



// MAC Config

#define CONFIG_ESP_MAC_ADDR_UNIVERSE_WIFI_STA 1
#define CONFIG_ESP_MAC_ADDR_UNIVERSE_BT 1
#define CONFIG_ESP32S3_UNIVERSAL_MAC_ADDRESSES_TWO 1
// #define CONFIG_ESP32S3_UNIVERSAL_MAC_ADDRESSES_FOUR
#define CONFIG_ESP32S3_UNIVERSAL_MAC_ADDRESSES 2
// end of MAC Config


// Sleep Config

#define CONFIG_ESP_SLEEP_RTC_BUS_ISO_WORKAROUND 1
// #define CONFIG_ESP_SLEEP_GPIO_RESET_WORKAROUND
#define CONFIG_ESP_SLEEP_PSRAM_LEAKAGE_WORKAROUND 1
#define CONFIG_ESP_SLEEP_FLASH_LEAKAGE_WORKAROUND 1
#define CONFIG_ESP_SLEEP_MSPI_NEED_ALL_IO_PU 1
#define CONFIG_ESP_SLEEP_GPIO_ENABLE_INTERNAL_RESISTORS 1
// end of Sleep Config


// RTC Clock Config

#define CONFIG_RTC_CLOCK_BBPLL_POWER_ON_WITH_USB 1
// end of RTC Clock Config
// end of Hardware Settings


// IPC (Inter-Processor Call)

#define CONFIG_ESP_IPC_TASK_STACK_SIZE 1024
#define CONFIG_ESP_IPC_USES_CALLERS_PRIORITY 1
#define CONFIG_ESP_IPC_ISR_ENABLE 1
// end of IPC (Inter-Processor Call)


// LCD and Touch Panel



// LCD Touch Drivers are maintained in the IDF Component Registry



// LCD Peripheral Configuration

#define CONFIG_LCD_PANEL_IO_FORMAT_BUF_SIZE 32
// #define CONFIG_LCD_RGB_ISR_IRAM_SAFE
// end of LCD Peripheral Configuration
// end of LCD and Touch Panel


// ESP NETIF Adapter

#define CONFIG_ESP_NETIF_IP_LOST_TIMER_INTERVAL 120
#define CONFIG_ESP_NETIF_TCPIP_LWIP 1
// #define CONFIG_ESP_NETIF_LOOPBACK
#define CONFIG_ESP_NETIF_TCPIP_ADAPTER_COMPATIBLE_LAYER 1
// end of ESP NETIF Adapter


// PHY

#define CONFIG_ESP_PHY_CALIBRATION_AND_DATA_STORAGE 1
// #define CONFIG_ESP_PHY_INIT_DATA_IN_PARTITION
#define CONFIG_ESP_PHY_MAX_WIFI_TX_POWER 20
#define CONFIG_ESP_PHY_MAX_TX_POWER 20
// #define CONFIG_ESP_PHY_REDUCE_TX_POWER
#define CONFIG_ESP_PHY_ENABLE_USB 1
#define CONFIG_ESP_PHY_RF_CAL_PARTIAL 1
// #define CONFIG_ESP_PHY_RF_CAL_NONE
// #define CONFIG_ESP_PHY_RF_CAL_FULL
#define CONFIG_ESP_PHY_CALIBRATION_MODE 0
// end of PHY


// Power Management

// #define CONFIG_PM_ENABLE
#define CONFIG_PM_POWER_DOWN_CPU_IN_LIGHT_SLEEP 1
#define CONFIG_PM_POWER_DOWN_TAGMEM_IN_LIGHT_SLEEP 1
// end of Power Management


// ESP Ringbuf

// #define CONFIG_RINGBUF_PLACE_FUNCTIONS_INTO_FLASH
// #define CONFIG_RINGBUF_PLACE_ISR_FUNCTIONS_INTO_FLASH
// end of ESP Ringbuf


// ESP System Settings

// #define CONFIG_ESP_SYSTEM_PANIC_PRINT_HALT
#define CONFIG_ESP_SYSTEM_PANIC_PRINT_REBOOT 1
// #define CONFIG_ESP_SYSTEM_PANIC_SILENT_REBOOT
// #define CONFIG_ESP_SYSTEM_PANIC_GDBSTUB
// #define CONFIG_ESP_SYSTEM_GDBSTUB_RUNTIME
#define CONFIG_ESP_SYSTEM_RTC_FAST_MEM_AS_HEAP_DEPCHECK 1
#define CONFIG_ESP_SYSTEM_ALLOW_RTC_FAST_MEM_AS_HEAP 1


// Memory protection

// end of Memory protection

#define CONFIG_ESP_SYSTEM_EVENT_QUEUE_SIZE 32
#define CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE 2048
#define CONFIG_ESP_MAIN_TASK_STACK_SIZE 4096
#define CONFIG_ESP_MAIN_TASK_AFFINITY_CPU0 1
// #define CONFIG_ESP_MAIN_TASK_AFFINITY_CPU1
// #define CONFIG_ESP_MAIN_TASK_AFFINITY_NO_AFFINITY
#define CONFIG_ESP_MAIN_TASK_AFFINITY 0x0
#define CONFIG_ESP_MINIMAL_SHARED_STACK_SIZE 2048
#define CONFIG_ESP_CONSOLE_UART_DEFAULT 1
// #define CONFIG_ESP_CONSOLE_USB_CDC
// #define CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG
// #define CONFIG_ESP_CONSOLE_UART_CUSTOM
// #define CONFIG_ESP_CONSOLE_NONE
// #define CONFIG_ESP_CONSOLE_SECONDARY_NONE
#define CONFIG_ESP_CONSOLE_SECONDARY_USB_SERIAL_JTAG 1
#define CONFIG_ESP_CONSOLE_UART 1
#define CONFIG_ESP_CONSOLE_MULTIPLE_UART 1
#define CONFIG_ESP_CONSOLE_UART_NUM 0
#define CONFIG_ESP_CONSOLE_UART_BAUDRATE 115200
#define CONFIG_ESP_INT_WDT 1
#define CONFIG_ESP_INT_WDT_TIMEOUT_MS 300
#define CONFIG_ESP_INT_WDT_CHECK_CPU1 1
#define CONFIG_ESP_TASK_WDT 1
#define CONFIG_ESP_TASK_WDT_PANIC 1
#define CONFIG_ESP_TASK_WDT_TIMEOUT_S 5
#define CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU0 1
// #define CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU1
// #define CONFIG_ESP_PANIC_HANDLER_IRAM
// #define CONFIG_ESP_DEBUG_STUBS_ENABLE
#define CONFIG_ESP_SYSTEM_CHECK_INT_LEVEL_4 1
#define CONFIG_ESP_SYSTEM_BBPLL_RECALIB 1
// end of ESP System Settings


// High resolution timer (esp_timer)

// #define CONFIG_ESP_TIMER_PROFILING
#define CONFIG_ESP_TIME_FUNCS_USE_RTC_TIMER 1
#define CONFIG_ESP_TIME_FUNCS_USE_ESP_TIMER 1
#define CONFIG_ESP_TIMER_TASK_STACK_SIZE 4096
#define CONFIG_ESP_TIMER_INTERRUPT_LEVEL 1
// #define CONFIG_ESP_TIMER_SUPPORTS_ISR_DISPATCH_METHOD
#define CONFIG_ESP_TIMER_IMPL_SYSTIMER 1
// end of High resolution timer (esp_timer)


// Wi-Fi

#define CONFIG_ESP32_WIFI_ENABLED 1
#define CONFIG_ESP32_WIFI_SW_COEXIST_ENABLE 1
#define CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM 8
#define CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM 32
#define CONFIG_ESP32_WIFI_STATIC_TX_BUFFER 1
#define CONFIG_ESP32_WIFI_TX_BUFFER_TYPE 0
#define CONFIG_ESP32_WIFI_STATIC_TX_BUFFER_NUM 8
#define CONFIG_ESP32_WIFI_CACHE_TX_BUFFER_NUM 16
#define CONFIG_ESP_WIFI_STATIC_RX_MGMT_BUFFER 1
// #define CONFIG_ESP_WIFI_DYNAMIC_RX_MGMT_BUFFER
#define CONFIG_ESP_WIFI_DYNAMIC_RX_MGMT_BUF 0
#define CONFIG_ESP_WIFI_RX_MGMT_BUF_NUM_DEF 5
#define CONFIG_ESP32_WIFI_CSI_ENABLED 1
#define CONFIG_ESP32_WIFI_AMPDU_TX_ENABLED 1
#define CONFIG_ESP32_WIFI_TX_BA_WIN 6
#define CONFIG_ESP32_WIFI_AMPDU_RX_ENABLED 1
#define CONFIG_ESP32_WIFI_RX_BA_WIN 16
// #define CONFIG_ESP32_WIFI_AMSDU_TX_ENABLED
#define CONFIG_ESP32_WIFI_NVS_ENABLED 1
#define CONFIG_ESP32_WIFI_TASK_PINNED_TO_CORE_0 1
// #define CONFIG_ESP32_WIFI_TASK_PINNED_TO_CORE_1
#define CONFIG_ESP32_WIFI_SOFTAP_BEACON_MAX_LEN 752
#define CONFIG_ESP32_WIFI_MGMT_SBUF_NUM 32
// #define CONFIG_ESP32_WIFI_IRAM_OPT
// #define CONFIG_ESP32_WIFI_RX_IRAM_OPT
#define CONFIG_ESP32_WIFI_ENABLE_WPA3_SAE 1
// #define CONFIG_ESP_WIFI_SLP_IRAM_OPT
#define CONFIG_ESP_WIFI_FTM_ENABLE 1
#define CONFIG_ESP_WIFI_FTM_INITIATOR_SUPPORT 1
#define CONFIG_ESP_WIFI_FTM_RESPONDER_SUPPORT 1
// #define CONFIG_ESP_WIFI_STA_DISCONNECTED_PM_ENABLE
// #define CONFIG_ESP_WIFI_GCMP_SUPPORT
// #define CONFIG_ESP_WIFI_GMAC_SUPPORT
#define CONFIG_ESP_WIFI_SOFTAP_SUPPORT 1
// #define CONFIG_ESP_WIFI_SLP_BEACON_LOST_OPT
#define CONFIG_ESP_WIFI_ESPNOW_MAX_ENCRYPT_NUM 7
// end of Wi-Fi


// Core dump

#define CONFIG_ESP_COREDUMP_ENABLE_TO_FLASH 1
// #define CONFIG_ESP_COREDUMP_ENABLE_TO_UART
// #define CONFIG_ESP_COREDUMP_ENABLE_TO_NONE
// #define CONFIG_ESP_COREDUMP_DATA_FORMAT_BIN
#define CONFIG_ESP_COREDUMP_DATA_FORMAT_ELF 1
#define CONFIG_ESP_COREDUMP_CHECKSUM_CRC32 1
#define CONFIG_ESP_COREDUMP_CHECK_BOOT 1
#define CONFIG_ESP_COREDUMP_ENABLE 1
#define CONFIG_ESP_COREDUMP_LOGS 1
#define CONFIG_ESP_COREDUMP_MAX_TASKS_NUM 64
#define CONFIG_ESP_COREDUMP_STACK_SIZE 1024
// end of Core dump


// FAT Filesystem support

// #define CONFIG_FATFS_CODEPAGE_DYNAMIC
// #define CONFIG_FATFS_CODEPAGE_437
// #define CONFIG_FATFS_CODEPAGE_720
// #define CONFIG_FATFS_CODEPAGE_737
// #define CONFIG_FATFS_CODEPAGE_771
// #define CONFIG_FATFS_CODEPAGE_775
#define CONFIG_FATFS_CODEPAGE_850 1
// #define CONFIG_FATFS_CODEPAGE_852
// #define CONFIG_FATFS_CODEPAGE_855
// #define CONFIG_FATFS_CODEPAGE_857
// #define CONFIG_FATFS_CODEPAGE_860
// #define CONFIG_FATFS_CODEPAGE_861
// #define CONFIG_FATFS_CODEPAGE_862
// #define CONFIG_FATFS_CODEPAGE_863
// #define CONFIG_FATFS_CODEPAGE_864
// #define CONFIG_FATFS_CODEPAGE_865
// #define CONFIG_FATFS_CODEPAGE_866
// #define CONFIG_FATFS_CODEPAGE_869
// #define CONFIG_FATFS_CODEPAGE_932
// #define CONFIG_FATFS_CODEPAGE_936
// #define CONFIG_FATFS_CODEPAGE_949
// #define CONFIG_FATFS_CODEPAGE_950
#define CONFIG_FATFS_CODEPAGE 850
// #define CONFIG_FATFS_LFN_NONE
// #define CONFIG_FATFS_LFN_HEAP
#define CONFIG_FATFS_LFN_STACK 1
#define CONFIG_FATFS_MAX_LFN 255
// #define CONFIG_FATFS_API_ENCODING_ANSI_OEM
// #define CONFIG_FATFS_API_ENCODING_UTF_16
#define CONFIG_FATFS_API_ENCODING_UTF_8 1
#define CONFIG_FATFS_FS_LOCK 0
#define CONFIG_FATFS_TIMEOUT_MS 10000
#define CONFIG_FATFS_PER_FILE_CACHE 1
#define CONFIG_FATFS_ALLOC_PREFER_EXTRAM 1
// #define CONFIG_FATFS_USE_FASTSEEK
// end of FAT Filesystem support


// Modbus configuration

#define CONFIG_FMB_COMM_MODE_TCP_EN 1
#define CONFIG_FMB_TCP_PORT_DEFAULT 502
#define CONFIG_FMB_TCP_PORT_MAX_CONN 5
#define CONFIG_FMB_TCP_CONNECTION_TOUT_SEC 20
#define CONFIG_FMB_COMM_MODE_RTU_EN 1
#define CONFIG_FMB_COMM_MODE_ASCII_EN 1
#define CONFIG_FMB_MASTER_TIMEOUT_MS_RESPOND 150
#define CONFIG_FMB_MASTER_DELAY_MS_CONVERT 200
#define CONFIG_FMB_QUEUE_LENGTH 20
#define CONFIG_FMB_PORT_TASK_STACK_SIZE 4096
#define CONFIG_FMB_SERIAL_BUF_SIZE 256
#define CONFIG_FMB_SERIAL_ASCII_BITS_PER_SYMB 8
#define CONFIG_FMB_SERIAL_ASCII_TIMEOUT_RESPOND_MS 1000
#define CONFIG_FMB_PORT_TASK_PRIO 10
// #define CONFIG_FMB_PORT_TASK_AFFINITY_NO_AFFINITY
#define CONFIG_FMB_PORT_TASK_AFFINITY_CPU0 1
// #define CONFIG_FMB_PORT_TASK_AFFINITY_CPU1
#define CONFIG_FMB_PORT_TASK_AFFINITY 0x0
// #define CONFIG_FMB_CONTROLLER_SLAVE_ID_SUPPORT
#define CONFIG_FMB_CONTROLLER_NOTIFY_TIMEOUT 20
#define CONFIG_FMB_CONTROLLER_NOTIFY_QUEUE_SIZE 20
#define CONFIG_FMB_CONTROLLER_STACK_SIZE 4096
#define CONFIG_FMB_EVENT_QUEUE_TIMEOUT 20
#define CONFIG_FMB_TIMER_PORT_ENABLED 1
// #define CONFIG_FMB_TIMER_USE_ISR_DISPATCH_METHOD
// end of Modbus configuration


// FreeRTOS

// #define CONFIG_FREERTOS_UNICORE
#define CONFIG_FREERTOS_NO_AFFINITY 0x7FFFFFFF
#define CONFIG_FREERTOS_TICK_SUPPORT_SYSTIMER 1
#define CONFIG_FREERTOS_CORETIMER_SYSTIMER_LVL1 1
// #define CONFIG_FREERTOS_CORETIMER_SYSTIMER_LVL3
#define CONFIG_FREERTOS_SYSTICK_USES_SYSTIMER 1
#define CONFIG_FREERTOS_HZ 1000
// #define CONFIG_FREERTOS_ASSERT_ON_UNTESTED_FUNCTION
// #define CONFIG_FREERTOS_CHECK_STACKOVERFLOW_NONE
// #define CONFIG_FREERTOS_CHECK_STACKOVERFLOW_PTRVAL
#define CONFIG_FREERTOS_CHECK_STACKOVERFLOW_CANARY 1
#define CONFIG_FREERTOS_WATCHPOINT_END_OF_STACK 1
#define CONFIG_FREERTOS_INTERRUPT_BACKTRACE 1
#define CONFIG_FREERTOS_THREAD_LOCAL_STORAGE_POINTERS 1
#define CONFIG_FREERTOS_ASSERT_FAIL_ABORT 1
// #define CONFIG_FREERTOS_ASSERT_FAIL_PRINT_CONTINUE
// #define CONFIG_FREERTOS_ASSERT_DISABLE
#define CONFIG_FREERTOS_IDLE_TASK_STACKSIZE 1024
#define CONFIG_FREERTOS_ISR_STACKSIZE 2096
// #define CONFIG_FREERTOS_LEGACY_HOOKS
#define CONFIG_FREERTOS_MAX_TASK_NAME_LEN 16
#define CONFIG_FREERTOS_SUPPORT_STATIC_ALLOCATION 1
// #define CONFIG_FREERTOS_ENABLE_STATIC_TASK_CLEAN_UP
#define CONFIG_FREERTOS_TIMER_TASK_PRIORITY 1
#define CONFIG_FREERTOS_TIMER_TASK_STACK_DEPTH 3120
#define CONFIG_FREERTOS_TIMER_QUEUE_LENGTH 10
#define CONFIG_FREERTOS_QUEUE_REGISTRY_SIZE 0
// #define CONFIG_FREERTOS_USE_TRACE_FACILITY
// #define CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS
#define CONFIG_FREERTOS_CHECK_MUTEX_GIVEN_BY_OWNER 1
// #define CONFIG_FREERTOS_CHECK_PORT_CRITICAL_COMPLIANCE
// #define CONFIG_FREERTOS_PLACE_FUNCTIONS_INTO_FLASH
#define CONFIG_FREERTOS_DEBUG_OCDAWARE 1
#define CONFIG_FREERTOS_ENABLE_TASK_SNAPSHOT 1
// #define CONFIG_FREERTOS_PLACE_SNAPSHOT_FUNS_INTO_FLASH
// end of FreeRTOS


// Hardware Abstraction Layer (HAL) and Low Level (LL)

#define CONFIG_HAL_ASSERTION_EQUALS_SYSTEM 1
// #define CONFIG_HAL_ASSERTION_DISABLE
// #define CONFIG_HAL_ASSERTION_SILIENT
// #define CONFIG_HAL_ASSERTION_ENABLE
#define CONFIG_HAL_DEFAULT_ASSERTION_LEVEL 2
// end of Hardware Abstraction Layer (HAL) and Low Level (LL)


// Heap memory debugging

// #define CONFIG_HEAP_POISONING_DISABLED
#define CONFIG_HEAP_POISONING_LIGHT 1
// #define CONFIG_HEAP_POISONING_COMPREHENSIVE
#define CONFIG_HEAP_TRACING_OFF 1
// #define CONFIG_HEAP_TRACING_STANDALONE
// #define CONFIG_HEAP_TRACING_TOHOST
// #define CONFIG_HEAP_TASK_TRACKING
// #define CONFIG_HEAP_ABORT_WHEN_ALLOCATION_FAILS
// end of Heap memory debugging


// jsmn

// #define CONFIG_JSMN_PARENT_LINKS
// #define CONFIG_JSMN_STRICT
// end of jsmn


// libsodium

// end of libsodium


// Log output

// #define CONFIG_LOG_DEFAULT_LEVEL_NONE
#define CONFIG_LOG_DEFAULT_LEVEL_ERROR 1
// #define CONFIG_LOG_DEFAULT_LEVEL_WARN
// #define CONFIG_LOG_DEFAULT_LEVEL_INFO
// #define CONFIG_LOG_DEFAULT_LEVEL_DEBUG
// #define CONFIG_LOG_DEFAULT_LEVEL_VERBOSE
#define CONFIG_LOG_DEFAULT_LEVEL 1
#define CONFIG_LOG_MAXIMUM_EQUALS_DEFAULT 1
// #define CONFIG_LOG_MAXIMUM_LEVEL_WARN
// #define CONFIG_LOG_MAXIMUM_LEVEL_INFO
// #define CONFIG_LOG_MAXIMUM_LEVEL_DEBUG
// #define CONFIG_LOG_MAXIMUM_LEVEL_VERBOSE
#define CONFIG_LOG_MAXIMUM_LEVEL 1
// #define CONFIG_LOG_COLORS
#define CONFIG_LOG_TIMESTAMP_SOURCE_RTOS 1
// #define CONFIG_LOG_TIMESTAMP_SOURCE_SYSTEM
// end of Log output


// LWIP

#define CONFIG_LWIP_LOCAL_HOSTNAME "espressif"
// #define CONFIG_LWIP_NETIF_API
#define CONFIG_LWIP_TCPIP_TASK_PRIO 18
// #define CONFIG_LWIP_TCPIP_CORE_LOCKING
// #define CONFIG_LWIP_CHECK_THREAD_SAFETY
#define CONFIG_LWIP_DNS_SUPPORT_MDNS_QUERIES 1
// #define CONFIG_LWIP_L2_TO_L3_COPY
// #define CONFIG_LWIP_IRAM_OPTIMIZATION
#define CONFIG_LWIP_TIMERS_ONDEMAND 1
#define CONFIG_LWIP_MAX_SOCKETS 16
// #define CONFIG_LWIP_USE_ONLY_LWIP_SELECT
// #define CONFIG_LWIP_SO_LINGER
#define CONFIG_LWIP_SO_REUSE 1
#define CONFIG_LWIP_SO_REUSE_RXTOALL 1
#define CONFIG_LWIP_SO_RCVBUF 1
// #define CONFIG_LWIP_NETBUF_RECVINFO
#define CONFIG_LWIP_IP_DEFAULT_TTL 64
#define CONFIG_LWIP_IP4_FRAG 1
#define CONFIG_LWIP_IP6_FRAG 1
// #define CONFIG_LWIP_IP4_REASSEMBLY
// #define CONFIG_LWIP_IP6_REASSEMBLY
// #define CONFIG_LWIP_IP_FORWARD
// #define CONFIG_LWIP_STATS
#define CONFIG_LWIP_ETHARP_TRUST_IP_MAC 1
#define CONFIG_LWIP_ESP_GRATUITOUS_ARP 1
#define CONFIG_LWIP_GARP_TMR_INTERVAL 60
#define CONFIG_LWIP_ESP_MLDV6_REPORT 1
#define CONFIG_LWIP_MLDV6_TMR_INTERVAL 40
#define CONFIG_LWIP_TCPIP_RECVMBOX_SIZE 32
// #define CONFIG_LWIP_DHCP_DOES_ARP_CHECK
// #define CONFIG_LWIP_DHCP_DISABLE_CLIENT_ID
#define CONFIG_LWIP_DHCP_DISABLE_VENDOR_CLASS_ID 1
#define CONFIG_LWIP_DHCP_RESTORE_LAST_IP 1
#define CONFIG_LWIP_DHCP_OPTIONS_LEN 128
#define CONFIG_LWIP_DHCP_COARSE_TIMER_SECS 1


// DHCP server

#define CONFIG_LWIP_DHCPS 1
#define CONFIG_LWIP_DHCPS_LEASE_UNIT 60
#define CONFIG_LWIP_DHCPS_MAX_STATION_NUM 8
// end of DHCP server

// #define CONFIG_LWIP_AUTOIP
#define CONFIG_LWIP_IPV6 1
#define CONFIG_LWIP_IPV6_AUTOCONFIG 1
#define CONFIG_LWIP_IPV6_NUM_ADDRESSES 3
// #define CONFIG_LWIP_IPV6_FORWARD
#define CONFIG_LWIP_IPV6_RDNSS_MAX_DNS_SERVERS 0
// #define CONFIG_LWIP_IPV6_DHCP6
// #define CONFIG_LWIP_NETIF_STATUS_CALLBACK
#define CONFIG_LWIP_NETIF_LOOPBACK 1
#define CONFIG_LWIP_LOOPBACK_MAX_PBUFS 8


// TCP

#define CONFIG_LWIP_MAX_ACTIVE_TCP 16
#define CONFIG_LWIP_MAX_LISTENING_TCP 16
#define CONFIG_LWIP_TCP_HIGH_SPEED_RETRANSMISSION 1
#define CONFIG_LWIP_TCP_MAXRTX 12
#define CONFIG_LWIP_TCP_SYNMAXRTX 6
#define CONFIG_LWIP_TCP_MSS 1436
#define CONFIG_LWIP_TCP_TMR_INTERVAL 250
#define CONFIG_LWIP_TCP_MSL 60000
#define CONFIG_LWIP_TCP_FIN_WAIT_TIMEOUT 20000
#define CONFIG_LWIP_TCP_SND_BUF_DEFAULT 5760
#define CONFIG_LWIP_TCP_WND_DEFAULT 5760
#define CONFIG_LWIP_TCP_RECVMBOX_SIZE 6
#define CONFIG_LWIP_TCP_QUEUE_OOSEQ 1
#define CONFIG_LWIP_TCP_OOSEQ_TIMEOUT 6
#define CONFIG_LWIP_TCP_OOSEQ_MAX_PBUFS 0
// #define CONFIG_LWIP_TCP_SACK_OUT
// #define CONFIG_LWIP_TCP_KEEP_CONNECTION_WHEN_IP_CHANGES
#define CONFIG_LWIP_TCP_OVERSIZE_MSS 1
// #define CONFIG_LWIP_TCP_OVERSIZE_QUARTER_MSS
// #define CONFIG_LWIP_TCP_OVERSIZE_DISABLE
// #define CONFIG_LWIP_WND_SCALE
#define CONFIG_LWIP_TCP_RTO_TIME 3000
// end of TCP


// UDP

#define CONFIG_LWIP_MAX_UDP_PCBS 16
#define CONFIG_LWIP_UDP_RECVMBOX_SIZE 6
// end of UDP


// Checksums

// #define CONFIG_LWIP_CHECKSUM_CHECK_IP
// #define CONFIG_LWIP_CHECKSUM_CHECK_UDP
#define CONFIG_LWIP_CHECKSUM_CHECK_ICMP 1
// end of Checksums

#define CONFIG_LWIP_TCPIP_TASK_STACK_SIZE 2560
// #define CONFIG_LWIP_TCPIP_TASK_AFFINITY_NO_AFFINITY
#define CONFIG_LWIP_TCPIP_TASK_AFFINITY_CPU0 1
// #define CONFIG_LWIP_TCPIP_TASK_AFFINITY_CPU1
#define CONFIG_LWIP_TCPIP_TASK_AFFINITY 0x0
// #define CONFIG_LWIP_PPP_SUPPORT
#define CONFIG_LWIP_IPV6_MEMP_NUM_ND6_QUEUE 3
#define CONFIG_LWIP_IPV6_ND6_NUM_NEIGHBORS 5
// #define CONFIG_LWIP_SLIP_SUPPORT


// ICMP

#define CONFIG_LWIP_ICMP 1
// #define CONFIG_LWIP_MULTICAST_PING
// #define CONFIG_LWIP_BROADCAST_PING
// end of ICMP


// LWIP RAW API

#define CONFIG_LWIP_MAX_RAW_PCBS 16
// end of LWIP RAW API


// SNTP

#define CONFIG_LWIP_SNTP_MAX_SERVERS 3
#define CONFIG_LWIP_DHCP_GET_NTP_SRV 1
#define CONFIG_LWIP_DHCP_MAX_NTP_SERVERS 1
#define CONFIG_LWIP_SNTP_UPDATE_DELAY 10800000
// end of SNTP


// DNS

#define CONFIG_LWIP_DNS_MAX_SERVERS 3
// #define CONFIG_LWIP_FALLBACK_DNS_SERVER_SUPPORT
// end of DNS

#define CONFIG_LWIP_ESP_LWIP_ASSERT 1


// Hooks

// #define CONFIG_LWIP_HOOK_TCP_ISN_NONE
#define CONFIG_LWIP_HOOK_TCP_ISN_DEFAULT 1
// #define CONFIG_LWIP_HOOK_TCP_ISN_CUSTOM
#define CONFIG_LWIP_HOOK_IP6_ROUTE_NONE 1
// #define CONFIG_LWIP_HOOK_IP6_ROUTE_DEFAULT
// #define CONFIG_LWIP_HOOK_IP6_ROUTE_CUSTOM
#define CONFIG_LWIP_HOOK_ND6_GET_GW_NONE 1
// #define CONFIG_LWIP_HOOK_ND6_GET_GW_DEFAULT
// #define CONFIG_LWIP_HOOK_ND6_GET_GW_CUSTOM
#define CONFIG_LWIP_HOOK_NETCONN_EXT_RESOLVE_NONE 1
// #define CONFIG_LWIP_HOOK_NETCONN_EXT_RESOLVE_DEFAULT
// #define CONFIG_LWIP_HOOK_NETCONN_EXT_RESOLVE_CUSTOM
// end of Hooks

// #define CONFIG_LWIP_DEBUG
// end of LWIP


// mbedTLS

#define CONFIG_MBEDTLS_INTERNAL_MEM_ALLOC 1
// #define CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC
// #define CONFIG_MBEDTLS_DEFAULT_MEM_ALLOC
// #define CONFIG_MBEDTLS_CUSTOM_MEM_ALLOC
#define CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN 16384
// #define CONFIG_MBEDTLS_ASYMMETRIC_CONTENT_LEN
// #define CONFIG_MBEDTLS_DEBUG


// mbedTLS v2.28.x related

// #define CONFIG_MBEDTLS_SSL_VARIABLE_BUFFER_LENGTH
// #define CONFIG_MBEDTLS_X509_TRUSTED_CERT_CALLBACK
// #define CONFIG_MBEDTLS_SSL_CONTEXT_SERIALIZATION
#define CONFIG_MBEDTLS_SSL_KEEP_PEER_CERTIFICATE 1


// DTLS-based configurations

// #define CONFIG_MBEDTLS_SSL_DTLS_CONNECTION_ID
// #define CONFIG_MBEDTLS_SSL_DTLS_SRTP
// end of DTLS-based configurations
// end of mbedTLS v2.28.x related


// Certificate Bundle

#define CONFIG_MBEDTLS_CERTIFICATE_BUNDLE 1
#define CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_DEFAULT_FULL 1
// #define CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_DEFAULT_CMN
// #define CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_DEFAULT_NONE
// #define CONFIG_MBEDTLS_CUSTOM_CERTIFICATE_BUNDLE
#define CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_MAX_CERTS 200
// end of Certificate Bundle

// #define CONFIG_MBEDTLS_ECP_RESTARTABLE
// #define CONFIG_MBEDTLS_CMAC_C
#define CONFIG_MBEDTLS_HARDWARE_AES 1
#define CONFIG_MBEDTLS_AES_USE_INTERRUPT 1
#define CONFIG_MBEDTLS_HARDWARE_MPI 1
#define CONFIG_MBEDTLS_HARDWARE_SHA 1
#define CONFIG_MBEDTLS_ROM_MD5 1
// #define CONFIG_MBEDTLS_ATCA_HW_ECDSA_SIGN
// #define CONFIG_MBEDTLS_ATCA_HW_ECDSA_VERIFY
#define CONFIG_MBEDTLS_HAVE_TIME 1
// #define CONFIG_MBEDTLS_HAVE_TIME_DATE
#define CONFIG_MBEDTLS_ECDSA_DETERMINISTIC 1
#define CONFIG_MBEDTLS_SHA512_C 1
#define CONFIG_MBEDTLS_TLS_SERVER_AND_CLIENT 1
// #define CONFIG_MBEDTLS_TLS_SERVER_ONLY
// #define CONFIG_MBEDTLS_TLS_CLIENT_ONLY
// #define CONFIG_MBEDTLS_TLS_DISABLED
#define CONFIG_MBEDTLS_TLS_SERVER 1
#define CONFIG_MBEDTLS_TLS_CLIENT 1
#define CONFIG_MBEDTLS_TLS_ENABLED 1


// TLS Key Exchange Methods

#define CONFIG_MBEDTLS_PSK_MODES 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_PSK 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_DHE_PSK 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_PSK 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_RSA_PSK 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_RSA 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_DHE_RSA 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ELLIPTIC_CURVE 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_RSA 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_RSA 1
// end of TLS Key Exchange Methods

#define CONFIG_MBEDTLS_SSL_RENEGOTIATION 1
// #define CONFIG_MBEDTLS_SSL_PROTO_SSL3
#define CONFIG_MBEDTLS_SSL_PROTO_TLS1 1
#define CONFIG_MBEDTLS_SSL_PROTO_TLS1_1 1
#define CONFIG_MBEDTLS_SSL_PROTO_TLS1_2 1
// #define CONFIG_MBEDTLS_SSL_PROTO_GMTSSL1_1
#define CONFIG_MBEDTLS_SSL_PROTO_DTLS 1
#define CONFIG_MBEDTLS_SSL_ALPN 1
#define CONFIG_MBEDTLS_CLIENT_SSL_SESSION_TICKETS 1
#define CONFIG_MBEDTLS_X509_CHECK_KEY_USAGE 1
#define CONFIG_MBEDTLS_X509_CHECK_EXTENDED_KEY_USAGE 1
#define CONFIG_MBEDTLS_SERVER_SSL_SESSION_TICKETS 1


// Symmetric Ciphers

#define CONFIG_MBEDTLS_AES_C 1
#define CONFIG_MBEDTLS_CAMELLIA_C 1
// #define CONFIG_MBEDTLS_DES_C
#define CONFIG_MBEDTLS_RC4_DISABLED 1
// #define CONFIG_MBEDTLS_RC4_ENABLED_NO_DEFAULT
// #define CONFIG_MBEDTLS_RC4_ENABLED
// #define CONFIG_MBEDTLS_BLOWFISH_C
// #define CONFIG_MBEDTLS_XTEA_C
#define CONFIG_MBEDTLS_CCM_C 1
#define CONFIG_MBEDTLS_GCM_C 1
// #define CONFIG_MBEDTLS_NIST_KW_C
// end of Symmetric Ciphers

// #define CONFIG_MBEDTLS_RIPEMD160_C


// Certificates

#define CONFIG_MBEDTLS_PEM_PARSE_C 1
#define CONFIG_MBEDTLS_PEM_WRITE_C 1
#define CONFIG_MBEDTLS_X509_CRL_PARSE_C 1
#define CONFIG_MBEDTLS_X509_CSR_PARSE_C 1
// end of Certificates

#define CONFIG_MBEDTLS_ECP_C 1
#define CONFIG_MBEDTLS_ECDH_C 1
#define CONFIG_MBEDTLS_ECDSA_C 1
// #define CONFIG_MBEDTLS_ECJPAKE_C
#define CONFIG_MBEDTLS_ECP_DP_SECP192R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP224R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP256R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP384R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP521R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP192K1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP224K1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP256K1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_BP256R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_BP384R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_BP512R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_CURVE25519_ENABLED 1
#define CONFIG_MBEDTLS_ECP_NIST_OPTIM 1
// #define CONFIG_MBEDTLS_POLY1305_C
// #define CONFIG_MBEDTLS_CHACHA20_C
// #define CONFIG_MBEDTLS_HKDF_C
// #define CONFIG_MBEDTLS_THREADING_C
// #define CONFIG_MBEDTLS_LARGE_KEY_SOFTWARE_MPI
// #define CONFIG_MBEDTLS_SECURITY_RISKS
// end of mbedTLS


// mDNS

#define CONFIG_MDNS_MAX_SERVICES 10
#define CONFIG_MDNS_TASK_PRIORITY 1
#define CONFIG_MDNS_TASK_STACK_SIZE 4096
// #define CONFIG_MDNS_TASK_AFFINITY_NO_AFFINITY
#define CONFIG_MDNS_TASK_AFFINITY_CPU0 1
// #define CONFIG_MDNS_TASK_AFFINITY_CPU1
#define CONFIG_MDNS_TASK_AFFINITY 0x0
#define CONFIG_MDNS_SERVICE_ADD_TIMEOUT_MS 2000
// #define CONFIG_MDNS_STRICT_MODE
#define CONFIG_MDNS_TIMER_PERIOD_MS 100
// #define CONFIG_MDNS_NETWORKING_SOCKET
#define CONFIG_MDNS_MULTIPLE_INSTANCE 1
// end of mDNS


// ESP-MQTT Configurations

#define CONFIG_MQTT_PROTOCOL_311 1
#define CONFIG_MQTT_TRANSPORT_SSL 1
#define CONFIG_MQTT_TRANSPORT_WEBSOCKET 1
#define CONFIG_MQTT_TRANSPORT_WEBSOCKET_SECURE 1
// #define CONFIG_MQTT_MSG_ID_INCREMENTAL
// #define CONFIG_MQTT_SKIP_PUBLISH_IF_DISCONNECTED
// #define CONFIG_MQTT_REPORT_DELETED_MESSAGES
// #define CONFIG_MQTT_USE_CUSTOM_CONFIG
// #define CONFIG_MQTT_TASK_CORE_SELECTION_ENABLED
// #define CONFIG_MQTT_CUSTOM_OUTBOX
// end of ESP-MQTT Configurations


// Newlib

#define CONFIG_NEWLIB_STDOUT_LINE_ENDING_CRLF 1
// #define CONFIG_NEWLIB_STDOUT_LINE_ENDING_LF
// #define CONFIG_NEWLIB_STDOUT_LINE_ENDING_CR
// #define CONFIG_NEWLIB_STDIN_LINE_ENDING_CRLF
// #define CONFIG_NEWLIB_STDIN_LINE_ENDING_LF
#define CONFIG_NEWLIB_STDIN_LINE_ENDING_CR 1
// #define CONFIG_NEWLIB_NANO_FORMAT
// end of Newlib


// NVS

// #define CONFIG_NVS_ASSERT_ERROR_CHECK
// end of NVS


// OpenSSL

// #define CONFIG_OPENSSL_DEBUG
#define CONFIG_OPENSSL_ERROR_STACK 1
#define CONFIG_OPENSSL_ASSERT_DO_NOTHING 1
// #define CONFIG_OPENSSL_ASSERT_EXIT
// end of OpenSSL


// OpenThread

// #define CONFIG_OPENTHREAD_ENABLED
// end of OpenThread


// PThreads

#define CONFIG_PTHREAD_TASK_PRIO_DEFAULT 5
#define CONFIG_PTHREAD_TASK_STACK_SIZE_DEFAULT 2048
#define CONFIG_PTHREAD_STACK_MIN 768
#define CONFIG_PTHREAD_DEFAULT_CORE_NO_AFFINITY 1
// #define CONFIG_PTHREAD_DEFAULT_CORE_0
// #define CONFIG_PTHREAD_DEFAULT_CORE_1
#define CONFIG_PTHREAD_TASK_CORE_DEFAULT -1
#define CONFIG_PTHREAD_TASK_NAME_DEFAULT "pthread"
// end of PThreads


// Main Flash configuration



// Optional and Experimental Features (READ DOCS FIRST)



// Features here require specific hardware (READ DOCS FIRST!)

// #define CONFIG_SPI_FLASH_HPM_ENA
#define CONFIG_SPI_FLASH_HPM_AUTO 1
// #define CONFIG_SPI_FLASH_HPM_DIS
#define CONFIG_SPI_FLASH_HPM_ON 1
#define CONFIG_SPI_FLASH_HPM_DC_AUTO 1
// #define CONFIG_SPI_FLASH_HPM_DC_DISABLE
// end of Optional and Experimental Features (READ DOCS FIRST)
// end of Main Flash configuration


// SPI Flash driver

// #define CONFIG_SPI_FLASH_VERIFY_WRITE
// #define CONFIG_SPI_FLASH_ENABLE_COUNTERS
#define CONFIG_SPI_FLASH_ROM_DRIVER_PATCH 1
// #define CONFIG_SPI_FLASH_ROM_IMPL
#define CONFIG_SPI_FLASH_DANGEROUS_WRITE_ABORTS 1
// #define CONFIG_SPI_FLASH_DANGEROUS_WRITE_FAILS
// #define CONFIG_SPI_FLASH_DANGEROUS_WRITE_ALLOWED
// #define CONFIG_SPI_FLASH_USE_LEGACY_IMPL
// #define CONFIG_SPI_FLASH_SHARE_SPI1_BUS
// #define CONFIG_SPI_FLASH_BYPASS_BLOCK_ERASE
#define CONFIG_SPI_FLASH_YIELD_DURING_ERASE 1
#define CONFIG_SPI_FLASH_ERASE_YIELD_DURATION_MS 10
#define CONFIG_SPI_FLASH_ERASE_YIELD_TICKS 2
#define CONFIG_SPI_FLASH_WRITE_CHUNK_SIZE 4096
// #define CONFIG_SPI_FLASH_SIZE_OVERRIDE
// #define CONFIG_SPI_FLASH_CHECK_ERASE_TIMEOUT_DISABLED
// #define CONFIG_SPI_FLASH_OVERRIDE_CHIP_DRIVER_LIST

// Auto-detect flash chips
#define CONFIG_SPI_FLASH_SUPPORT_ISSI_CHIP 1
#define CONFIG_SPI_FLASH_SUPPORT_MXIC_CHIP 1
#define CONFIG_SPI_FLASH_SUPPORT_GD_CHIP 1
#define CONFIG_SPI_FLASH_SUPPORT_WINBOND_CHIP 1
#define CONFIG_SPI_FLASH_SUPPORT_BOYA_CHIP 1
#define CONFIG_SPI_FLASH_SUPPORT_TH_CHIP 1
#define CONFIG_SPI_FLASH_SUPPORT_MXIC_OPI_CHIP 1
// end of Auto-detect flash chips

#define CONFIG_SPI_FLASH_ENABLE_ENCRYPTED_READ_WRITE 1
// end of SPI Flash driver

// SPIFFS Configuration
#define CONFIG_SPIFFS_MAX_PARTITIONS 3

// SPIFFS Cache Configuration
#define CONFIG_SPIFFS_CACHE 1
#define CONFIG_SPIFFS_CACHE_WR 1
// #define CONFIG_SPIFFS_CACHE_STATS
// end of SPIFFS Cache Configuration

#define CONFIG_SPIFFS_PAGE_CHECK 1
#define CONFIG_SPIFFS_GC_MAX_RUNS 10
// #define CONFIG_SPIFFS_GC_STATS
#define CONFIG_SPIFFS_PAGE_SIZE 256
#define CONFIG_SPIFFS_OBJ_NAME_LEN 32
// #define CONFIG_SPIFFS_FOLLOW_SYMLINKS
#define CONFIG_SPIFFS_USE_MAGIC 1
#define CONFIG_SPIFFS_USE_MAGIC_LENGTH 1
#define CONFIG_SPIFFS_META_LENGTH 4
#define CONFIG_SPIFFS_USE_MTIME 1

// Debug Configuration
// #define CONFIG_SPIFFS_DBG
// #define CONFIG_SPIFFS_API_DBG
// #define CONFIG_SPIFFS_GC_DBG
// #define CONFIG_SPIFFS_CACHE_DBG
// #define CONFIG_SPIFFS_CHECK_DBG
// #define CONFIG_SPIFFS_TEST_VISUALISATION
// end of Debug Configuration
// end of SPIFFS Configuration

// TCP Transport

// Websocket
#define CONFIG_WS_TRANSPORT 1
#define CONFIG_WS_BUFFER_SIZE 1024
// end of Websocket
// end of TCP Transport

// TinyUSB Stack
// #define CONFIG_TINYUSB
// end of TinyUSB Stack

// Unity unit testing library
#define CONFIG_UNITY_ENABLE_FLOAT 1
#define CONFIG_UNITY_ENABLE_DOUBLE 1
// #define CONFIG_UNITY_ENABLE_64BIT
// #define CONFIG_UNITY_ENABLE_COLOR
#define CONFIG_UNITY_ENABLE_IDF_TEST_RUNNER 1
// #define CONFIG_UNITY_ENABLE_FIXTURE
// #define CONFIG_UNITY_ENABLE_BACKTRACE_ON_FAIL
// end of Unity unit testing library

// USB-OTG
#define CONFIG_USB_OTG_SUPPORTED 1
#define CONFIG_USB_HOST_CONTROL_TRANSFER_MAX_SIZE 256
#define CONFIG_USB_HOST_HW_BUFFER_BIAS_BALANCED 1
// #define CONFIG_USB_HOST_HW_BUFFER_BIAS_IN
// #define CONFIG_USB_HOST_HW_BUFFER_BIAS_PERIODIC_OUT


// Root Hub configuration

#define CONFIG_USB_HOST_DEBOUNCE_DELAY_MS 250
#define CONFIG_USB_HOST_RESET_HOLD_MS 30
#define CONFIG_USB_HOST_RESET_RECOVERY_MS 30
#define CONFIG_USB_HOST_SET_ADDR_RECOVERY_MS 10
// end of Root Hub configuration
// end of USB-OTG


// Virtual file system

#define CONFIG_VFS_SUPPORT_IO 1
#define CONFIG_VFS_SUPPORT_DIR 1
#define CONFIG_VFS_SUPPORT_SELECT 1
#define CONFIG_VFS_SUPPRESS_SELECT_DEBUG_OUTPUT 1
#define CONFIG_VFS_SUPPORT_TERMIOS 1


// Host File System I/O (Semihosting)

#define CONFIG_VFS_SEMIHOSTFS_MAX_MOUNT_POINTS 1
// end of Host File System I/O (Semihosting)
// end of Virtual file system


// Wear Levelling

// #define CONFIG_WL_SECTOR_SIZE_512
#define CONFIG_WL_SECTOR_SIZE_4096 1
#define CONFIG_WL_SECTOR_SIZE 4096
// end of Wear Levelling


// Wi-Fi Provisioning Manager

#define CONFIG_WIFI_PROV_SCAN_MAX_ENTRIES 16
#define CONFIG_WIFI_PROV_AUTOSTOP_TIMEOUT 30
// #define CONFIG_WIFI_PROV_BLE_BONDING
// #define CONFIG_WIFI_PROV_BLE_FORCE_ENCRYPTION
// #define CONFIG_WIFI_PROV_KEEP_BLE_ON_AFTER_PROV
// end of Wi-Fi Provisioning Manager


// Supplicant

#define CONFIG_WPA_MBEDTLS_CRYPTO 1
// #define CONFIG_WPA_WAPI_PSK
// #define CONFIG_WPA_SUITE_B_192
// #define CONFIG_WPA_DEBUG_PRINT
// #define CONFIG_WPA_TESTING_OPTIONS
// #define CONFIG_WPA_WPS_STRICT
// #define CONFIG_WPA_11KV_SUPPORT
// #define CONFIG_WPA_MBO_SUPPORT
// #define CONFIG_WPA_DPP_SUPPORT
// end of Supplicant


// Diagnostics

#define CONFIG_DIAG_LOG_MSG_ARG_FORMAT_TLV 1
// #define CONFIG_DIAG_LOG_MSG_ARG_FORMAT_STRING
#define CONFIG_DIAG_LOG_MSG_ARG_MAX_SIZE 64
#define CONFIG_DIAG_LOG_DROP_WIFI_LOGS 1
#define CONFIG_DIAG_ENABLE_METRICS 1
#define CONFIG_DIAG_METRICS_MAX_COUNT 20
#define CONFIG_DIAG_ENABLE_HEAP_METRICS 1
#define CONFIG_DIAG_ENABLE_WIFI_METRICS 1
#define CONFIG_DIAG_ENABLE_VARIABLES 1
#define CONFIG_DIAG_VARIABLES_MAX_COUNT 20
#define CONFIG_DIAG_ENABLE_NETWORK_VARIABLES 1
// #define CONFIG_DIAG_MORE_NETWORK_VARS
// end of Diagnostics


// ESP Insights

#define CONFIG_ESP_INSIGHTS_ENABLED 1
// #define CONFIG_ESP_INSIGHTS_DEBUG_ENABLED
#define CONFIG_ESP_INSIGHTS_COREDUMP_ENABLE 1
// #define CONFIG_ESP_INSIGHTS_TRANSPORT_MQTT
#define CONFIG_ESP_INSIGHTS_TRANSPORT_HTTPS 1
#define CONFIG_ESP_INSIGHTS_TRANSPORT_HTTPS_HOST "https://client.insights.espressif.com"
#define CONFIG_ESP_INSIGHTS_CLOUD_POST_MIN_INTERVAL_SEC 60
#define CONFIG_ESP_INSIGHTS_CLOUD_POST_MAX_INTERVAL_SEC 240
// end of ESP Insights


// ESP RainMaker Common

#define CONFIG_ESP_RMAKER_LIB_ESP_MQTT 1
// #define CONFIG_ESP_RMAKER_LIB_AWS_IOT
#define CONFIG_ESP_RMAKER_MQTT_GLUE_LIB 1
#define CONFIG_ESP_RMAKER_MQTT_PORT_443 1
// #define CONFIG_ESP_RMAKER_MQTT_PORT_8883
#define CONFIG_ESP_RMAKER_MQTT_PORT 1
// #define CONFIG_ESP_RMAKER_MQTT_PERSISTENT_SESSION
#define CONFIG_ESP_RMAKER_MQTT_SEND_USERNAME 1
#define CONFIG_ESP_RMAKER_MQTT_PRODUCT_NAME "RMDev"
#define CONFIG_ESP_RMAKER_MQTT_PRODUCT_VERSION "1x0"
#define CONFIG_ESP_RMAKER_MQTT_PRODUCT_SKU "EX00"
#define CONFIG_ESP_RMAKER_MQTT_USE_CERT_BUNDLE 1
#define CONFIG_ESP_RMAKER_MAX_MQTT_SUBSCRIPTIONS 10
#define CONFIG_ESP_RMAKER_WORK_QUEUE_TASK_STACK 4096
#define CONFIG_ESP_RMAKER_WORK_QUEUE_TASK_PRIORITY 5
#define CONFIG_ESP_RMAKER_FACTORY_PARTITION_NAME "fctry"
#define CONFIG_ESP_RMAKER_FACTORY_NAMESPACE "rmaker_creds"
#define CONFIG_ESP_RMAKER_DEF_TIMEZONE "Asia/Shanghai"
#define CONFIG_ESP_RMAKER_SNTP_SERVER_NAME "pool.ntp.org"
#define CONFIG_ESP_RMAKER_MAX_COMMANDS 10
// end of ESP RainMaker Common


// RTC Store

#define CONFIG_RTC_STORE_DATA_SIZE 6144
#define CONFIG_RTC_STORE_CRITICAL_DATA_SIZE 4096
#define CONFIG_RTC_STORE_REPORTING_WATERMARK_PERCENT 80
// #define CONFIG_RTC_STORE_OVERWRITE_NON_CRITICAL_DATA
// end of RTC Store


// GPIO Button

#define CONFIG_IO_GLITCH_FILTER_TIME_MS 50
// end of GPIO Button


// WS2812 RGB LED

// #define CONFIG_WS2812_LED_ENABLE
// end of WS2812 RGB LED


// Camera configuration

#define CONFIG_OV7670_SUPPORT 1
#define CONFIG_OV7725_SUPPORT 1
#define CONFIG_NT99141_SUPPORT 1
#define CONFIG_OV2640_SUPPORT 1
#define CONFIG_OV3660_SUPPORT 1
#define CONFIG_OV5640_SUPPORT 1
#define CONFIG_GC2145_SUPPORT 1
#define CONFIG_GC032A_SUPPORT 1
#define CONFIG_GC0308_SUPPORT 1
#define CONFIG_BF3005_SUPPORT 1
#define CONFIG_BF20A6_SUPPORT 1
// #define CONFIG_SC101IOT_SUPPORT
#define CONFIG_SC030IOT_SUPPORT 1
// #define CONFIG_SC031GS_SUPPORT
// #define CONFIG_SCCB_HARDWARE_I2C_PORT0
#define CONFIG_SCCB_HARDWARE_I2C_PORT1 1
#define CONFIG_SCCB_CLK_FREQ 100000
// #define CONFIG_GC_SENSOR_WINDOWING_MODE
#define CONFIG_GC_SENSOR_SUBSAMPLE_MODE 1
#define CONFIG_CAMERA_TASK_STACK_SIZE 2048
#define CONFIG_CAMERA_CORE0 1
// #define CONFIG_CAMERA_CORE1
// #define CONFIG_CAMERA_NO_AFFINITY
#define CONFIG_CAMERA_DMA_BUFFER_SIZE_MAX 32768
// #define CONFIG_CAMERA_CONVERTER_ENABLED
// #define CONFIG_LCD_CAM_ISR_IRAM_SAFE
// end of Camera configuration


// LittleFS

// #define CONFIG_LITTLEFS_SDMMC_SUPPORT
#define CONFIG_LITTLEFS_MAX_PARTITIONS 3
#define CONFIG_LITTLEFS_PAGE_SIZE 256
#define CONFIG_LITTLEFS_OBJ_NAME_LEN 64
#define CONFIG_LITTLEFS_READ_SIZE 128
#define CONFIG_LITTLEFS_WRITE_SIZE 128
#define CONFIG_LITTLEFS_LOOKAHEAD_SIZE 128
#define CONFIG_LITTLEFS_CACHE_SIZE 512
#define CONFIG_LITTLEFS_BLOCK_CYCLES 512
#define CONFIG_LITTLEFS_USE_MTIME 1
// #define CONFIG_LITTLEFS_USE_ONLY_HASH
// #define CONFIG_LITTLEFS_HUMAN_READABLE
#define CONFIG_LITTLEFS_MTIME_USE_SECONDS 1
// #define CONFIG_LITTLEFS_MTIME_USE_NONCE
// #define CONFIG_LITTLEFS_SPIFFS_COMPAT
// #define CONFIG_LITTLEFS_FLUSH_FILE_EVERY_WRITE
// #define CONFIG_LITTLEFS_FCNTL_GET_PATH
// #define CONFIG_LITTLEFS_MULTIVERSION
// #define CONFIG_LITTLEFS_MALLOC_STRATEGY_DISABLE
#define CONFIG_LITTLEFS_MALLOC_STRATEGY_DEFAULT 1
// #define CONFIG_LITTLEFS_MALLOC_STRATEGY_INTERNAL
#define CONFIG_LITTLEFS_ASSERTS 1
// end of LittleFS


// DSP Library

#define CONFIG_DSP_OPTIMIZATIONS_SUPPORTED 1
// #define CONFIG_DSP_ANSI
#define CONFIG_DSP_OPTIMIZED 1
#define CONFIG_DSP_OPTIMIZATION 1
// #define CONFIG_DSP_MAX_FFT_SIZE_512
// #define CONFIG_DSP_MAX_FFT_SIZE_1024
// #define CONFIG_DSP_MAX_FFT_SIZE_2048
#define CONFIG_DSP_MAX_FFT_SIZE_4096 1
// #define CONFIG_DSP_MAX_FFT_SIZE_8192
// #define CONFIG_DSP_MAX_FFT_SIZE_16384
// #define CONFIG_DSP_MAX_FFT_SIZE_32768
#define CONFIG_DSP_MAX_FFT_SIZE 4096
// end of DSP Library


// ESP Secure Cert Manager

#define CONFIG_ESP_SECURE_CERT_DS_PERIPHERAL 1
// #define CONFIG_ESP_SECURE_CERT_SUPPORT_LEGACY_FORMATS
// end of ESP Secure Cert Manager
// end of Component config


// Compatibility options

// #define CONFIG_LEGACY_INCLUDE_COMMON_HEADERS
// end of Compatibility options

// Deprecated options for backward compatibility
#define CONFIG_TOOLPREFIX "xtensa-esp32s3-elf-"
#define CONFIG_LOG_BOOTLOADER_LEVEL_NONE 1
// #define CONFIG_LOG_BOOTLOADER_LEVEL_ERROR
// #define CONFIG_LOG_BOOTLOADER_LEVEL_WARN
// #define CONFIG_LOG_BOOTLOADER_LEVEL_INFO
// #define CONFIG_LOG_BOOTLOADER_LEVEL_DEBUG
// #define CONFIG_LOG_BOOTLOADER_LEVEL_VERBOSE
#define CONFIG_LOG_BOOTLOADER_LEVEL 0
#define CONFIG_APP_ROLLBACK_ENABLE 1
// #define CONFIG_APP_ANTI_ROLLBACK
// #define CONFIG_FLASH_ENCRYPTION_ENABLED
#define CONFIG_FLASHMODE_QIO 1
// #define CONFIG_FLASHMODE_QOUT
// #define CONFIG_FLASHMODE_DIO
// #define CONFIG_FLASHMODE_DOUT
// #define CONFIG_MONITOR_BAUD_9600B
// #define CONFIG_MONITOR_BAUD_57600B
#define CONFIG_MONITOR_BAUD_115200B 1
// #define CONFIG_MONITOR_BAUD_230400B
// #define CONFIG_MONITOR_BAUD_921600B
// #define CONFIG_MONITOR_BAUD_2MB
// #define CONFIG_MONITOR_BAUD_OTHER
#define CONFIG_MONITOR_BAUD_OTHER_VAL 115200
#define CONFIG_MONITOR_BAUD 115200
// #define CONFIG_ESP_RMAKER_LOCAL_CTRL_ENABLE
#define CONFIG_USB_CDC_ENABLED 1
#define CONFIG_USB_DESC_CDC_STRING "Espressif CDC Device"
#define CONFIG_USB_CDC_RX_BUFSIZE 64
#define CONFIG_USB_CDC_TX_BUFSIZE 64
#define CONFIG_USB_MSC_ENABLED 1
#define CONFIG_USB_DESC_MSC_STRING "Espressif MSC Device"
#define CONFIG_USB_MSC_BUFSIZE 4096
#define CONFIG_USB_DESC_HID_STRING "Espressif HID Device"
#define CONFIG_USB_DEBUG_LEVEL 0
// #define CONFIG_COMPILER_OPTIMIZATION_LEVEL_DEBUG
#define CONFIG_COMPILER_OPTIMIZATION_LEVEL_RELEASE 1
#define CONFIG_OPTIMIZATION_ASSERTIONS_ENABLED 1
// #define CONFIG_OPTIMIZATION_ASSERTIONS_SILENT
// #define CONFIG_OPTIMIZATION_ASSERTIONS_DISABLED
#define CONFIG_OPTIMIZATION_ASSERTION_LEVEL 2
#define CONFIG_CXX_EXCEPTIONS 1
#define CONFIG_CXX_EXCEPTIONS_EMG_POOL_SIZE 0
// #define CONFIG_STACK_CHECK_NONE
#define CONFIG_STACK_CHECK_NORM 1
// #define CONFIG_STACK_CHECK_STRONG
// #define CONFIG_STACK_CHECK_ALL
#define CONFIG_STACK_CHECK 1
#define CONFIG_WARN_WRITE_STRINGS 1
// #define CONFIG_DISABLE_GCC8_WARNINGS
// #define CONFIG_ESP32_APPTRACE_DEST_TRAX
#define CONFIG_ESP32_APPTRACE_DEST_NONE 1
#define CONFIG_ESP32_APPTRACE_LOCK_ENABLE 1
#define CONFIG_BLUEDROID_ENABLED 1
// #define CONFIG_NIMBLE_ENABLED
#define CONFIG_BTC_TASK_STACK_SIZE 3072
#define CONFIG_BLUEDROID_PINNED_TO_CORE_0 1
// #define CONFIG_BLUEDROID_PINNED_TO_CORE_1
#define CONFIG_BLUEDROID_PINNED_TO_CORE 0
#define CONFIG_BTU_TASK_STACK_SIZE 4352
// #define CONFIG_BLUEDROID_MEM_DEBUG
#define CONFIG_GATTS_ENABLE 1
// #define CONFIG_GATTS_SEND_SERVICE_CHANGE_MANUAL
#define CONFIG_GATTS_SEND_SERVICE_CHANGE_AUTO 1
#define CONFIG_GATTS_SEND_SERVICE_CHANGE_MODE 0
#define CONFIG_GATTC_ENABLE 1
// #define CONFIG_GATTC_CACHE_NVS_FLASH
#define CONFIG_BLE_SMP_ENABLE 1
// #define CONFIG_SMP_SLAVE_CON_PARAMS_UPD_ENABLE
// #define CONFIG_HCI_TRACE_LEVEL_NONE
// #define CONFIG_HCI_TRACE_LEVEL_ERROR
#define CONFIG_HCI_TRACE_LEVEL_WARNING 1
// #define CONFIG_HCI_TRACE_LEVEL_API
// #define CONFIG_HCI_TRACE_LEVEL_EVENT
// #define CONFIG_HCI_TRACE_LEVEL_DEBUG
// #define CONFIG_HCI_TRACE_LEVEL_VERBOSE
#define CONFIG_HCI_INITIAL_TRACE_LEVEL 2
// #define CONFIG_BTM_TRACE_LEVEL_NONE
// #define CONFIG_BTM_TRACE_LEVEL_ERROR
#define CONFIG_BTM_TRACE_LEVEL_WARNING 1
// #define CONFIG_BTM_TRACE_LEVEL_API
// #define CONFIG_BTM_TRACE_LEVEL_EVENT
// #define CONFIG_BTM_TRACE_LEVEL_DEBUG
// #define CONFIG_BTM_TRACE_LEVEL_VERBOSE
#define CONFIG_BTM_INITIAL_TRACE_LEVEL 2
// #define CONFIG_L2CAP_TRACE_LEVEL_NONE
// #define CONFIG_L2CAP_TRACE_LEVEL_ERROR
#define CONFIG_L2CAP_TRACE_LEVEL_WARNING 1
// #define CONFIG_L2CAP_TRACE_LEVEL_API
// #define CONFIG_L2CAP_TRACE_LEVEL_EVENT
// #define CONFIG_L2CAP_TRACE_LEVEL_DEBUG
// #define CONFIG_L2CAP_TRACE_LEVEL_VERBOSE
#define CONFIG_L2CAP_INITIAL_TRACE_LEVEL 2
// #define CONFIG_RFCOMM_TRACE_LEVEL_NONE
// #define CONFIG_RFCOMM_TRACE_LEVEL_ERROR
#define CONFIG_RFCOMM_TRACE_LEVEL_WARNING 1
// #define CONFIG_RFCOMM_TRACE_LEVEL_API
// #define CONFIG_RFCOMM_TRACE_LEVEL_EVENT
// #define CONFIG_RFCOMM_TRACE_LEVEL_DEBUG
// #define CONFIG_RFCOMM_TRACE_LEVEL_VERBOSE
#define CONFIG_RFCOMM_INITIAL_TRACE_LEVEL 2
// #define CONFIG_SDP_TRACE_LEVEL_NONE
// #define CONFIG_SDP_TRACE_LEVEL_ERROR
#define CONFIG_SDP_TRACE_LEVEL_WARNING 1
// #define CONFIG_SDP_TRACE_LEVEL_API
// #define CONFIG_SDP_TRACE_LEVEL_EVENT
// #define CONFIG_SDP_TRACE_LEVEL_DEBUG
// #define CONFIG_SDP_TRACE_LEVEL_VERBOSE
#define CONFIG_BTH_LOG_SDP_INITIAL_TRACE_LEVEL 2
// #define CONFIG_GAP_TRACE_LEVEL_NONE
// #define CONFIG_GAP_TRACE_LEVEL_ERROR
#define CONFIG_GAP_TRACE_LEVEL_WARNING 1
// #define CONFIG_GAP_TRACE_LEVEL_API
// #define CONFIG_GAP_TRACE_LEVEL_EVENT
// #define CONFIG_GAP_TRACE_LEVEL_DEBUG
// #define CONFIG_GAP_TRACE_LEVEL_VERBOSE
#define CONFIG_GAP_INITIAL_TRACE_LEVEL 2
#define CONFIG_BNEP_INITIAL_TRACE_LEVEL 2
// #define CONFIG_PAN_TRACE_LEVEL_NONE
// #define CONFIG_PAN_TRACE_LEVEL_ERROR
#define CONFIG_PAN_TRACE_LEVEL_WARNING 1
// #define CONFIG_PAN_TRACE_LEVEL_API
// #define CONFIG_PAN_TRACE_LEVEL_EVENT
// #define CONFIG_PAN_TRACE_LEVEL_DEBUG
// #define CONFIG_PAN_TRACE_LEVEL_VERBOSE
#define CONFIG_PAN_INITIAL_TRACE_LEVEL 2
// #define CONFIG_A2D_TRACE_LEVEL_NONE
// #define CONFIG_A2D_TRACE_LEVEL_ERROR
#define CONFIG_A2D_TRACE_LEVEL_WARNING 1
// #define CONFIG_A2D_TRACE_LEVEL_API
// #define CONFIG_A2D_TRACE_LEVEL_EVENT
// #define CONFIG_A2D_TRACE_LEVEL_DEBUG
// #define CONFIG_A2D_TRACE_LEVEL_VERBOSE
#define CONFIG_A2D_INITIAL_TRACE_LEVEL 2
// #define CONFIG_AVDT_TRACE_LEVEL_NONE
// #define CONFIG_AVDT_TRACE_LEVEL_ERROR
#define CONFIG_AVDT_TRACE_LEVEL_WARNING 1
// #define CONFIG_AVDT_TRACE_LEVEL_API
// #define CONFIG_AVDT_TRACE_LEVEL_EVENT
// #define CONFIG_AVDT_TRACE_LEVEL_DEBUG
// #define CONFIG_AVDT_TRACE_LEVEL_VERBOSE
#define CONFIG_AVDT_INITIAL_TRACE_LEVEL 2
// #define CONFIG_AVCT_TRACE_LEVEL_NONE
// #define CONFIG_AVCT_TRACE_LEVEL_ERROR
#define CONFIG_AVCT_TRACE_LEVEL_WARNING 1
// #define CONFIG_AVCT_TRACE_LEVEL_API
// #define CONFIG_AVCT_TRACE_LEVEL_EVENT
// #define CONFIG_AVCT_TRACE_LEVEL_DEBUG
// #define CONFIG_AVCT_TRACE_LEVEL_VERBOSE
#define CONFIG_AVCT_INITIAL_TRACE_LEVEL 2
// #define CONFIG_AVRC_TRACE_LEVEL_NONE
// #define CONFIG_AVRC_TRACE_LEVEL_ERROR
#define CONFIG_AVRC_TRACE_LEVEL_WARNING 1
// #define CONFIG_AVRC_TRACE_LEVEL_API
// #define CONFIG_AVRC_TRACE_LEVEL_EVENT
// #define CONFIG_AVRC_TRACE_LEVEL_DEBUG
// #define CONFIG_AVRC_TRACE_LEVEL_VERBOSE
#define CONFIG_AVRC_INITIAL_TRACE_LEVEL 2
// #define CONFIG_MCA_TRACE_LEVEL_NONE
// #define CONFIG_MCA_TRACE_LEVEL_ERROR
#define CONFIG_MCA_TRACE_LEVEL_WARNING 1
// #define CONFIG_MCA_TRACE_LEVEL_API
// #define CONFIG_MCA_TRACE_LEVEL_EVENT
// #define CONFIG_MCA_TRACE_LEVEL_DEBUG
// #define CONFIG_MCA_TRACE_LEVEL_VERBOSE
#define CONFIG_MCA_INITIAL_TRACE_LEVEL 2
// #define CONFIG_HID_TRACE_LEVEL_NONE
// #define CONFIG_HID_TRACE_LEVEL_ERROR
#define CONFIG_HID_TRACE_LEVEL_WARNING 1
// #define CONFIG_HID_TRACE_LEVEL_API
// #define CONFIG_HID_TRACE_LEVEL_EVENT
// #define CONFIG_HID_TRACE_LEVEL_DEBUG
// #define CONFIG_HID_TRACE_LEVEL_VERBOSE
#define CONFIG_HID_INITIAL_TRACE_LEVEL 2
// #define CONFIG_APPL_TRACE_LEVEL_NONE
// #define CONFIG_APPL_TRACE_LEVEL_ERROR
#define CONFIG_APPL_TRACE_LEVEL_WARNING 1
// #define CONFIG_APPL_TRACE_LEVEL_API
// #define CONFIG_APPL_TRACE_LEVEL_EVENT
// #define CONFIG_APPL_TRACE_LEVEL_DEBUG
// #define CONFIG_APPL_TRACE_LEVEL_VERBOSE
#define CONFIG_APPL_INITIAL_TRACE_LEVEL 2
// #define CONFIG_GATT_TRACE_LEVEL_NONE
// #define CONFIG_GATT_TRACE_LEVEL_ERROR
#define CONFIG_GATT_TRACE_LEVEL_WARNING 1
// #define CONFIG_GATT_TRACE_LEVEL_API
// #define CONFIG_GATT_TRACE_LEVEL_EVENT
// #define CONFIG_GATT_TRACE_LEVEL_DEBUG
// #define CONFIG_GATT_TRACE_LEVEL_VERBOSE
#define CONFIG_GATT_INITIAL_TRACE_LEVEL 2
// #define CONFIG_SMP_TRACE_LEVEL_NONE
// #define CONFIG_SMP_TRACE_LEVEL_ERROR
#define CONFIG_SMP_TRACE_LEVEL_WARNING 1
// #define CONFIG_SMP_TRACE_LEVEL_API
// #define CONFIG_SMP_TRACE_LEVEL_EVENT
// #define CONFIG_SMP_TRACE_LEVEL_DEBUG
// #define CONFIG_SMP_TRACE_LEVEL_VERBOSE
#define CONFIG_SMP_INITIAL_TRACE_LEVEL 2
// #define CONFIG_BTIF_TRACE_LEVEL_NONE
// #define CONFIG_BTIF_TRACE_LEVEL_ERROR
#define CONFIG_BTIF_TRACE_LEVEL_WARNING 1
// #define CONFIG_BTIF_TRACE_LEVEL_API
// #define CONFIG_BTIF_TRACE_LEVEL_EVENT
// #define CONFIG_BTIF_TRACE_LEVEL_DEBUG
// #define CONFIG_BTIF_TRACE_LEVEL_VERBOSE
#define CONFIG_BTIF_INITIAL_TRACE_LEVEL 2
// #define CONFIG_BTC_TRACE_LEVEL_NONE
// #define CONFIG_BTC_TRACE_LEVEL_ERROR
#define CONFIG_BTC_TRACE_LEVEL_WARNING 1
// #define CONFIG_BTC_TRACE_LEVEL_API
// #define CONFIG_BTC_TRACE_LEVEL_EVENT
// #define CONFIG_BTC_TRACE_LEVEL_DEBUG
// #define CONFIG_BTC_TRACE_LEVEL_VERBOSE
#define CONFIG_BTC_INITIAL_TRACE_LEVEL 2
// #define CONFIG_OSI_TRACE_LEVEL_NONE
// #define CONFIG_OSI_TRACE_LEVEL_ERROR
#define CONFIG_OSI_TRACE_LEVEL_WARNING 1
// #define CONFIG_OSI_TRACE_LEVEL_API
// #define CONFIG_OSI_TRACE_LEVEL_EVENT
// #define CONFIG_OSI_TRACE_LEVEL_DEBUG
// #define CONFIG_OSI_TRACE_LEVEL_VERBOSE
#define CONFIG_OSI_INITIAL_TRACE_LEVEL 2
// #define CONFIG_BLUFI_TRACE_LEVEL_NONE
// #define CONFIG_BLUFI_TRACE_LEVEL_ERROR
#define CONFIG_BLUFI_TRACE_LEVEL_WARNING 1
// #define CONFIG_BLUFI_TRACE_LEVEL_API
// #define CONFIG_BLUFI_TRACE_LEVEL_EVENT
// #define CONFIG_BLUFI_TRACE_LEVEL_DEBUG
// #define CONFIG_BLUFI_TRACE_LEVEL_VERBOSE
#define CONFIG_BLUFI_INITIAL_TRACE_LEVEL 2
// #define CONFIG_BLE_HOST_QUEUE_CONGESTION_CHECK
#define CONFIG_SMP_ENABLE 1
// #define CONFIG_BLE_ACTIVE_SCAN_REPORT_ADV_SCAN_RSP_INDIVIDUALLY
#define CONFIG_BLE_ESTABLISH_LINK_CONNECTION_TIMEOUT 30
// #define CONFIG_BLE_MESH_ALLOC_FROM_PSRAM_FIRST
#define CONFIG_ADC2_DISABLE_DAC 1
#define CONFIG_DEFAULT_PSRAM_CLK_IO 30
#define CONFIG_DEFAULT_PSRAM_CS_IO 26
// #define CONFIG_EVENT_LOOP_PROFILING
#define CONFIG_POST_EVENTS_FROM_ISR 1
#define CONFIG_POST_EVENTS_FROM_IRAM_ISR 1
// #define CONFIG_ESP32C3_LIGHTSLEEP_GPIO_RESET_WORKAROUND
#define CONFIG_IPC_TASK_STACK_SIZE 1024
#define CONFIG_ESP32_PHY_CALIBRATION_AND_DATA_STORAGE 1
// #define CONFIG_ESP32_PHY_INIT_DATA_IN_PARTITION
#define CONFIG_ESP32_PHY_MAX_WIFI_TX_POWER 20
#define CONFIG_ESP32_PHY_MAX_TX_POWER 20
// #define CONFIG_ESP32_REDUCE_PHY_TX_POWER
#define CONFIG_ESP_SYSTEM_PM_POWER_DOWN_CPU 1
// #define CONFIG_ESP32S2_PANIC_PRINT_HALT
#define CONFIG_ESP32S2_PANIC_PRINT_REBOOT 1
// #define CONFIG_ESP32S2_PANIC_SILENT_REBOOT
// #define CONFIG_ESP32S2_PANIC_GDBSTUB
#define CONFIG_ESP32S2_ALLOW_RTC_FAST_MEM_AS_HEAP 1
#define CONFIG_SYSTEM_EVENT_QUEUE_SIZE 32
#define CONFIG_SYSTEM_EVENT_TASK_STACK_SIZE 2048
#define CONFIG_MAIN_TASK_STACK_SIZE 4096
#define CONFIG_CONSOLE_UART_DEFAULT 1
// #define CONFIG_CONSOLE_UART_CUSTOM
// #define CONFIG_ESP_CONSOLE_UART_NONE
#define CONFIG_CONSOLE_UART 1
#define CONFIG_CONSOLE_UART_NUM 0
#define CONFIG_CONSOLE_UART_BAUDRATE 115200
#define CONFIG_INT_WDT 1
#define CONFIG_INT_WDT_TIMEOUT_MS 300
#define CONFIG_INT_WDT_CHECK_CPU1 1
#define CONFIG_TASK_WDT 1
#define CONFIG_TASK_WDT_PANIC 1
#define CONFIG_TASK_WDT_TIMEOUT_S 5
#define CONFIG_TASK_WDT_CHECK_IDLE_TASK_CPU0 1
// #define CONFIG_TASK_WDT_CHECK_IDLE_TASK_CPU1
// #define CONFIG_ESP32_DEBUG_STUBS_ENABLE
#define CONFIG_TIMER_TASK_STACK_SIZE 4096
#define CONFIG_SW_COEXIST_ENABLE 1
#define CONFIG_ESP32_ENABLE_COREDUMP_TO_FLASH 1
// #define CONFIG_ESP32_ENABLE_COREDUMP_TO_UART
// #define CONFIG_ESP32_ENABLE_COREDUMP_TO_NONE
// #define CONFIG_ESP32_COREDUMP_DATA_FORMAT_BIN
#define CONFIG_ESP32_COREDUMP_DATA_FORMAT_ELF 1
#define CONFIG_ESP32_COREDUMP_CHECKSUM_CRC32 1
#define CONFIG_ESP32_ENABLE_COREDUMP 1
#define CONFIG_ESP32_CORE_DUMP_MAX_TASKS_NUM 64
#define CONFIG_ESP32_CORE_DUMP_STACK_SIZE 1024
#define CONFIG_MB_MASTER_TIMEOUT_MS_RESPOND 150
#define CONFIG_MB_MASTER_DELAY_MS_CONVERT 200
#define CONFIG_MB_QUEUE_LENGTH 20
#define CONFIG_MB_SERIAL_TASK_STACK_SIZE 4096
#define CONFIG_MB_SERIAL_BUF_SIZE 256
#define CONFIG_MB_SERIAL_TASK_PRIO 10
// #define CONFIG_MB_CONTROLLER_SLAVE_ID_SUPPORT
#define CONFIG_MB_CONTROLLER_NOTIFY_TIMEOUT 20
#define CONFIG_MB_CONTROLLER_NOTIFY_QUEUE_SIZE 20
#define CONFIG_MB_CONTROLLER_STACK_SIZE 4096
#define CONFIG_MB_EVENT_QUEUE_TIMEOUT 20
#define CONFIG_MB_TIMER_PORT_ENABLED 1
// #define CONFIG_ENABLE_STATIC_TASK_CLEAN_UP_HOOK
#define CONFIG_TIMER_TASK_PRIORITY 1
#define CONFIG_TIMER_TASK_STACK_DEPTH 3120
#define CONFIG_TIMER_QUEUE_LENGTH 10
// #define CONFIG_L2_TO_L3_COPY
// #define CONFIG_USE_ONLY_LWIP_SELECT
#define CONFIG_ESP_GRATUITOUS_ARP 1
#define CONFIG_GARP_TMR_INTERVAL 60
#define CONFIG_TCPIP_RECVMBOX_SIZE 32
#define CONFIG_TCP_MAXRTX 12
#define CONFIG_TCP_SYNMAXRTX 6
#define CONFIG_TCP_MSS 1436
#define CONFIG_TCP_MSL 60000
#define CONFIG_TCP_SND_BUF_DEFAULT 5760
#define CONFIG_TCP_WND_DEFAULT 5760
#define CONFIG_TCP_RECVMBOX_SIZE 6
#define CONFIG_TCP_QUEUE_OOSEQ 1
// #define CONFIG_ESP_TCP_KEEP_CONNECTION_WHEN_IP_CHANGES
#define CONFIG_TCP_OVERSIZE_MSS 1
// #define CONFIG_TCP_OVERSIZE_QUARTER_MSS
// #define CONFIG_TCP_OVERSIZE_DISABLE
#define CONFIG_UDP_RECVMBOX_SIZE 6
#define CONFIG_TCPIP_TASK_STACK_SIZE 2560
// #define CONFIG_TCPIP_TASK_AFFINITY_NO_AFFINITY
#define CONFIG_TCPIP_TASK_AFFINITY_CPU0 1
// #define CONFIG_TCPIP_TASK_AFFINITY_CPU1
#define CONFIG_TCPIP_TASK_AFFINITY 0x0
// #define CONFIG_PPP_SUPPORT
#define CONFIG_ESP32_PTHREAD_TASK_PRIO_DEFAULT 5
#define CONFIG_ESP32_PTHREAD_TASK_STACK_SIZE_DEFAULT 2048
#define CONFIG_ESP32_PTHREAD_STACK_MIN 768
#define CONFIG_ESP32_DEFAULT_PTHREAD_CORE_NO_AFFINITY 1
// #define CONFIG_ESP32_DEFAULT_PTHREAD_CORE_0
// #define CONFIG_ESP32_DEFAULT_PTHREAD_CORE_1
#define CONFIG_ESP32_PTHREAD_TASK_CORE_DEFAULT -1
#define CONFIG_ESP32_PTHREAD_TASK_NAME_DEFAULT "pthread"
#define CONFIG_SPI_FLASH_WRITING_DANGEROUS_REGIONS_ABORTS 1
// #define CONFIG_SPI_FLASH_WRITING_DANGEROUS_REGIONS_FAILS
// #define CONFIG_SPI_FLASH_WRITING_DANGEROUS_REGIONS_ALLOWED
// #define CONFIG_USB_ENABLED
#define CONFIG_USB_DEBUG_LEVEL 0
#define CONFIG_USB_DESC_CDC_STRING "Espressif CDC Device"
#define CONFIG_USB_DESC_MSC_STRING "Espressif MSC Device"
#define CONFIG_USB_DESC_HID_STRING "Espressif HID Device"
#define CONFIG_USB_MSC_ENABLED 1
#define CONFIG_USB_MSC_BUFSIZE 4096
#define CONFIG_USB_CDC_ENABLED 1
#define CONFIG_USB_CDC_RX_BUFSIZE 64
#define CONFIG_USB_CDC_TX_BUFSIZE 64
#define CONFIG_SUPPRESS_SELECT_DEBUG_OUTPUT 1
#define CONFIG_SUPPORT_TERMIOS 1
#define CONFIG_SEMIHOSTFS_MAX_MOUNT_POINTS 1
// End of deprecated options

#endif
